- app/views/dashboard/index.njk
- app/views/profile/academic-qualifications/index.njk
- app/views/profile/academic-qualifications/review.njk
- app/views/profile/contact-details/enter-address.njk
- app/views/profile/contact-details/index.njk
- app/views/profile/contact-details/lookup-address.njk
- app/views/profile/contact-details/review.njk
- app/views/profile/contact-details/select-address.njk
- app/views/profile/index.njk
- app/views/profile/motivation.njk
- app/views/profile/personal-details/index.njk
- app/views/profile/professional-skills/index.njk
- app/views/profile/professional-skills/languages.njk
- app/views/profile/references/index.njk
- app/views/profile/references/review.njk
- app/views/profile/school-experience/index.njk
- app/views/profile/school-experience/overview.njk
- app/views/profile/subject-knowledge.njk
- app/views/profile/work-history/index.njk
- app/views/profile/work-history/overview.njk
Content update from Laura Tennant
> Globally replace 'Your Teaching Potential' with 'Your details'

- app/views/profile/subject-knowledge.njk
Based on evidence provided in high level findings document.
> Ask candidate why interested in taking SKE

- app/views/profile/subject-knowledge.njk
> Update subject knowledge

- app/views/profile/index.njk
- app/views/profile/motivation.njk
- app/views/profile/school-experience/index.njk
- app/views/profile/subject-knowledge.njk
Content updates to subject knowledge and school experience
> Content updates to subject knowledge and school experience

- app/views/courses/interview.njk
- app/views/profile/academic-qualifications/degree-details.njk
- app/views/profile/academic-qualifications/qualification.njk
- app/views/profile/index.njk
- app/views/profile/references/index.njk
- app/views/profile/subject-knowledge.njk
> Content updates

- app/views/profile/work-history/index.njk
- app/views/profile/work-history/job.njk
> Content updates 19.6.19

- app/views/profile/index.njk
- app/views/profile/vocation.njk
> Your teaching vocation

- app/views/profile/personal-details/index.njk
- app/views/profile/work-history/index.njk
> Date of birth

- app/routes.js
- app/views/profile/academic-qualifications/review.njk
- app/views/profile/index.njk
- app/views/profile/personal-details/index.njk
- app/views/profile/personal-details/review.njk
- app/views/profile/professional-skills/languages.njk
- app/views/profile/professional-skills/review.njk
- app/views/profile/references/referee.njk
- app/views/profile/references/review.njk
- app/views/profile/school-experience/review.njk
- app/views/profile/work-history/job.njk
- app/views/profile/work-history/review.njk
Start recording (and allow users to review) answers, initially within each relevant section after answering them. Will later experiment with showing summaries on application overview page.
> Review answers

- app/views/profile/motivation.njk
> Content changes 24.6.19

- app/views/dashboard/index.njk
- app/views/profile/personal-details/index.njk
- app/views/profile/personal-details/residency-status.njk
> Personal details

- app/views/courses/index.njk
- app/views/dashboard/index.njk
- app/views/profile/index.njk
> Start page content changes

- app/views/profile/contact-details/index.njk
- app/views/profile/personal-details/index.njk
- app/views/profile/personal-details/residency-status.njk
- app/views/profile/qualifications/degree-details.njk
- app/views/profile/qualifications/gcse-details.njk
> Qual content changes

- app/views/apply/review.njk
- app/views/apply/submit.njk
- app/views/dashboard/index.njk
Submission page content changes
> Submission page content changes

- app/views/account/create-account.njk
- app/views/profile/contact-details/index.njk
- app/views/profile/qualifications/degree-details.njk
> International degree changes

- app/views/profile/qualifications/degree-details.njk
- app/views/profile/qualifications/gcse-details.njk
- app/views/profile/qualifications/review.njk
- app/views/profile/subject-knowledge/index.njk
> GCSE non-UK qual updates

- app/views/index.njk
- app/views/profile/work-history/index.njk
- app/views/profile/work-history/missing.njk
> Out of workplace

- app/assets/sass/application.scss
- app/assets/sass/components/_icon.scss
- app/views/_components/icon/macro.njk
- app/views/_components/icon/template.njk
- app/views/_includes/review-work-history.njk
- app/views/_layout.njk
- app/views/account/create-account.njk
- app/views/profile/personal-details/index.njk
Adds a small tick icon (😱) alongside “This role involved working with children.” text on work history.
> Working with children indicator

- app/views/apply/confirmation.njk
> Application submitted content

- app/views/_includes/review-qualifications.njk
- app/views/apply/review.njk
- app/views/apply/submit.njk
- app/views/index.njk
- app/views/profile/qualifications/index.njk
- app/views/profile/qualifications/review.njk
- app/views/profile/vocation/index.njk
> Content tweaks post UR

- app/views/profile/language-skills/index.njk
- app/views/profile/references/index.njk
> Language skills

- app/routes.js
- app/views/_components/autocomplete/template.njk
- app/views/dashboard/index.njk
- app/views/profile/index.njk
- app/views/profile/language-skills/index.njk
- app/views/profile/qualifications/review.njk
- app/views/profile/subject-knowledge/index.njk
> Content-changes-1.8.19

- app/views/account/check-email.njk
- app/views/account/create-account.njk
> Magic link

- app/views/profile/references/index.njk
> Use of bold

- app/data/session-data-defaults.js
- app/routes.js
- app/views/application/work-history/index.njk
- app/views/application/work-history/job.njk
Asks candidates to explain their work history situation, providing appropriate guidance before directing them to the relevant page.
> Add branching logic to work history guidance

- app/views/application/work-history/index.njk
- app/views/application/work-history/missing.njk
> Work history content

- app/views/application/confirmation.njk
- app/views/application/references/review.njk
> Content tweaks (2019-08-07)

- app/views/application/subject-knowledge/index.njk
> Subject knowledge

- app/views/index.njk
> Start page

- app/views/application/confirmation.njk
- app/views/application/contact-details/address.njk
- app/views/application/contact-details/index.njk
- app/views/application/contact-details/lookup-address.njk
- app/views/application/contact-details/select-address.njk
- app/views/application/interview/index.njk
- app/views/application/subject-knowledge/index.njk
- app/views/application/submit.njk
- app/views/application/vocation/index.njk
Labels remain a work in progress, but this is more consistent than what we have currently.
> Consistent heading and label sizes/spacing

- app/routes.js
- app/utils/journeys.js
- app/views/course/find.njk
- app/views/course/found.njk
- server.js
> Find a course if you don’t know what to apply to

- app/views/application/references/index.njk
- app/views/application/references/referee-details.njk
- app/views/application/references/referee.njk
- app/views/application/references/review.njk
> Referee content

- app/data/session-data-defaults.js
- app/routes.js
- app/views/_includes/review-contact-details.njk
- app/views/_includes/review-personal-details.njk
- app/views/_includes/review-subject-knowledge.njk
- app/views/_includes/review-vocation.njk
- app/views/_layout.njk
- app/views/application/contact-details/address.njk
- app/views/application/contact-details/index.njk
- app/views/application/contact-details/lookup-address.njk
- app/views/application/contact-details/select-address.njk
- app/views/application/degree/review.njk
- app/views/application/index.njk
- app/views/application/interview/index.njk
- app/views/application/other-qualifications/review.njk
- app/views/application/personal-details/index.njk
- app/views/application/personal-details/residency-status.njk
- app/views/application/qualifications/index.njk
- app/views/application/qualifications/review.njk
- app/views/application/references/index.njk
- app/views/application/references/review.njk
- app/views/application/review.njk
- app/views/application/school-experience/index.njk
- app/views/application/school-experience/review.njk
- app/views/application/subject-knowledge/index.njk
- app/views/application/vocation/index.njk
- app/views/application/work-history/index.njk
- app/views/application/work-history/review.njk
- Adds Back links to the easy use cases
- Removes add/edit logic, show the same page whether editing or not
- Fix default course choices
> Replace breadcrumbs with Back links

- app/views/account/create-account.njk
- app/views/course/found.njk
- app/views/course/pick.njk
- app/views/course/provider.njk
- app/views/email/confirm-address.njk
> Add course content

- app/assets/sass/components/_caption.scss
- app/views/_includes/review-contact-details.njk
- app/views/_includes/review-courses.njk
- app/views/_includes/review-degree.njk
- app/views/_includes/review-gcse.njk
- app/views/_includes/review-interview.njk
- app/views/_includes/review-other-qualifications.njk
- app/views/_includes/review-personal-details.njk
- app/views/_includes/review-school-experience.njk
- app/views/_includes/review-subject-knowledge.njk
- app/views/_includes/review-vocation.njk
- app/views/_includes/review-work-history.njk
- app/views/application/index.njk
- app/views/application/review.njk
> Increase text size on application index and when reviewing

- app/routes.js
- app/routes/course.js
- app/routes/degree.js
- app/routes/gcse.js
- app/routes/other-qualifications.js
- app/utils/index.js
- app/utils/journeys.js
- app/views/_includes/review-gcse.njk
- app/views/_includes/review-school-experience.njk
- app/views/_includes/review-work-history.njk
- app/views/application/degree/grade.njk
- app/views/application/degree/index.njk
- app/views/application/degree/naric.njk
- app/views/application/degree/review.njk
- app/views/application/degree/year.njk
- app/views/application/gcse/grade.njk
- app/views/application/gcse/index.njk
- app/views/application/gcse/naric.njk
- app/views/application/gcse/year.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/other-qualifications/review.njk
- app/views/application/school-experience/review.njk
- app/views/application/school-experience/role.njk
- app/views/application/work-history/job.njk
- app/views/application/work-history/missing.njk
- app/views/application/work-history/review.njk
Adds back links to:
- work history
- school experience
- degree
- GCSEs
- other qualifications
> Add back links to the more complex sections

- app/assets/sass/application.scss
- app/assets/sass/components/_tag.scss
- app/data/session-data-defaults.js
- app/routes/application.js
- app/utils/filters-with-app-context.js
- app/utils/index.js
- app/views/_includes/application-courses.njk
- app/views/_includes/review-courses.njk
- app/views/_includes/review-references.njk
- app/views/application/confirmation.njk
- app/views/application/index.njk
- app/views/application/submitted.njk
- app/views/applications/index.njk
- Show submitted applications in /applications
- Redirect /applications if none submitted yet
- Add helpers for checking applications status
- Create a "submitted application" view
- Tweak display of courses on review application
> Submittable applications

- app/routes/application/references.js
- app/views/account/sign-in.njk
- app/views/application/degree/grade.njk
- app/views/application/degree/index.njk
- app/views/application/degree/naric.njk
- app/views/application/degree/year.njk
- app/views/application/gcse/grade.njk
- app/views/application/gcse/index.njk
- app/views/application/gcse/naric.njk
- app/views/application/gcse/year.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/references/details.njk
- app/views/application/references/index.njk
- app/views/application/references/type.njk
- app/views/application/school-experience/role.njk
- app/views/application/work-history/gap.njk
- app/views/application/work-history/job.njk
- app/views/index.njk
- Consistent label styles
- Update label text around NARIC questions (degree and GCSE equivalencies)
- Add back links for referee questions
> Design tweaks n fixes

- app/views/application/contact-details/index.njk
- app/views/application/other-qualifications/review.njk
- app/views/index.njk
> Content tweaks

- app/views/application/gcse/naric.njk
> Naric tweak

- app/views/_includes/review-contact-details.njk
- app/views/account/change-email-address.njk
- app/views/account/check-email.njk
- app/views/application/contact-details/index.njk
- app/views/email/confirm-address.njk
- Adds link on contact details question to change account email
- Adds a page allowing you to change your account email
Content needs tweaking before we can merge, @laurahermionetennant92.
> Add ability to change account email

- app/assets/sass/components/_summary.scss
- app/views/_includes/review-vocation.njk
- app/views/application/index.njk
- app/views/application/review.njk
* Group subject knowledge and vocation under personal statement header
* Stylistic fixes for summary table border
* Inter-paragraph/heading spacing on application page
> Group subject knowledge and vocation under personal statement header

- app/data/session-data-defaults.js
- app/routes/application/gcse.js
- app/views/_includes/review-gcse.njk
- app/views/_includes/review-vocation.njk
- app/views/application/degree/grade.njk
- app/views/application/degree/index.njk
- app/views/application/gcse/index.njk
- app/views/application/index.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/review.njk
- app/views/application/school-experience/role.njk
- app/views/application/submitted.njk
- app/views/application/vocation/index.njk
- app/views/application/vocation/review.njk
- app/views/applications/review.njk
> Content changes

- app/views/email/application-submitted.njk
> Update email submission

- app/views/application/gcse/index.njk
> Add additional guidance for science GCSE

- app/views/application/confirmation.njk
- app/views/email/application-submitted.njk
> Submission changes

- app/routes/application.js
- app/views/application/confirmation.njk
Fixes bug where clicking "View application" would show you an email.
> Avoid route clash between email and submitted application

- app/data/session-data-defaults.js
- app/routes/course.js
- app/views/_includes/review-courses.njk
- app/views/course/location.njk
Some courses let you select which location you want to be in. Use a hardcoded list for now.
> Pick a course location

- app/data/session-data-defaults.js
- app/views/_includes/review-personal-details.njk
- app/views/application/personal-details/index.njk
> Better display of language skills in personal details review

- app/views/_includes/review-gcse.njk
- app/views/application/degree/index.njk
- app/views/application/gcse/naric.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/submit.njk
- app/views/applications/index.njk
> Content bugs

- app/views/application/degree/index.njk
* Title: Add degree
* Hint for type: For example, BA, BSc or other (please specify)
* Title: Add another degree
* Hint for type: For example, Masters, PhD, or other (please specify)
* Title: Edit degree
* Hint for type: For example, BA, BSc, Masters, PhD, or other (please specify)
> Improved guidance for multiple degrees. Fixes #158

- lib/template.env
- lib/template.session-data-defaults.js
- package.json
- server.js
- start.js
- Use MongoDB for session storage
- Update node dependencies
- Add a template files included in the prototype kit (as warnings thrown in logs if not present)
> Store submitted data in a database

- app/views/application/degree/grade.njk
* Show structured classes
* Have you completed _your_ degree?
* I am still studying for _my_ degree
* Have you completed _this_ degree?
* I am still studying for _this_ degree
> Degree grade content

- app/views/_layout.njk
- server.js
- Add `UR_STUDY` environment variable
- Show ‘Clear data‘ link only if not `UR_STUDY` is not set to true
- Simplify phase banner text
- Add email link to footer (‘Give feedback or report a problem’)
> First few changes to prepare for UR research

- app/routes/application/equality-monitoring.js
- app/views/_includes/review-equality-monitoring.njk
- app/views/application/equality-monitoring/disabilities.njk
- app/views/application/equality-monitoring/disability-status.njk
- app/views/application/equality-monitoring/ethnic-background.njk
- app/views/application/equality-monitoring/ethnic-group.njk
- app/views/application/equality-monitoring/index.njk
- app/views/application/equality-monitoring/religious-belief.njk
- app/views/application/equality-monitoring/review.njk
- app/views/application/equality-monitoring/sex.njk
- app/views/application/equality-monitoring/sexual-orientation.njk
> Equality tweaks

- app/data/session-data-defaults.js
- app/routes/application/contact-details.js
- app/routes/application/degree.js
- app/views/_includes/review-contact-details.njk
- app/views/_includes/review-degrees.njk
- app/views/_includes/review-personal-details.njk
- app/views/application/contact-details/uk-address.njk
- app/views/application/degree/index.njk
- app/views/application/gcse/index.njk
- app/views/application/personal-details/index.njk
Allow us to turn off:
- nationality
- international addresses
- address lookup
- international qualifications
> Add feature flags

- app/data/session-data-defaults.js
Address lookup doesn't work and may be confusing without a moderator explaining.
> Disable address lookup

- app/routes/application.js
- app/views/application/submit.njk
- Adds export endpoint to retrieve JSON for a given application ID
- Moves answers to miscellaneous questions on submit page to application object
/cc @fofr
> Enable easier JSON export

- app/assets/sass/components/_summary-card.scss
- app/routes.js
- app/routes/delete.js
- app/views/_includes/review/degrees.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/_includes/review/references.njk
- app/views/_includes/review/school-experience.njk
- app/views/_includes/review/work-history.njk
- app/views/application/delete.njk
- app/views/application/work-history/gap.njk
> Work history tweaks

- app/views/application/equality-monitoring/index.njk
> Diversity tweak

- app/views/index.njk
> Full fat disability

- app/routes/delete.js
- app/views/_includes/item/role.njk
- app/views/_includes/review/school-experience.njk
- app/views/application/index.njk
- app/views/application/review.njk
- app/views/application/school-experience/index.njk
- app/views/application/school-experience/review.njk
- app/views/application/school-experience/role.njk
- app/views/application/submitted.njk
- app/views/application/work-history/job.njk
School experience content change
> School experience content change

- app/views/_includes/review/work-history.njk
- app/views/application/personal-statement/subject-knowledge.njk
- app/views/application/work-history/break.njk
- app/views/application/work-history/index.njk
- app/views/index.njk
More work history and subject knowledge stuff
> More work history and subject knowledge stuff

- app/data/session-data-defaults.js
- app/routes/apply.js
- app/views/_includes/application-courses.njk
- app/views/apply/get-into-teaching.njk
- app/views/apply/index.njk
- app/views/course/find.njk
- Provide a route from Find to Apply
- Make Find url configurable
> Enable journeys between Find prototype and Apply

- app/views/email/welcome.njk
> Content update welcome email

- app/views/apply/index.njk
- app/views/apply/providers.njk
Content participating providers
> Content participating providers

- app/views/apply/eligibility.njk
- app/views/apply/get-into-teaching.njk
- app/views/apply/index.njk
> Content DfE Apply nix

- app/assets/sass/components/_related.scss
- app/views/_components/related/template.njk
- app/views/application/index.njk
- app/views/applications/index.njk
- Add sidebar content for application/applications pages pointing to help contacts.
- Make text in related component larger, increasing width of top border.
> More prominent help on index pages

- app/views/application/choices/index.njk
> Choose courses content

- app/data/session-data-defaults.js
- app/routes/application/choices.js
- app/routes/apply.js
- app/views/application/choices/found.njk
- app/views/application/choices/pick.njk
- app/views/application/choices/provider.njk
> Allow selection of a pre-filled course choice from Find

- app/views/application/contact-details/index.njk
- app/views/application/contact-details/international-address.njk
- app/views/application/contact-details/select-address.njk
- app/views/application/contact-details/uk-address.njk
- app/views/application/contact-details/where-do-you-live.njk
- app/views/application/degree/grade.njk
- app/views/application/degree/index.njk
- app/views/application/degree/naric.njk
- app/views/application/degree/year.njk
- app/views/application/gcse/grade.njk
- app/views/application/gcse/index.njk
- app/views/application/gcse/naric.njk
- app/views/application/gcse/year.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/personal-details/index.njk
- app/views/application/personal-details/residency-status.njk
- app/views/application/personal-statement/interview.njk
- app/views/application/personal-statement/subject-knowledge.njk
- app/views/application/personal-statement/vocation.njk
- app/views/application/references/details.njk
- app/views/application/references/index.njk
- app/views/application/references/review.njk
- app/views/application/references/type.njk
- app/views/application/school-experience/index.njk
- app/views/application/school-experience/role.njk
- app/views/application/work-history/job.njk
Inform the user when something will be saved.
Keep "Continue" button for review pages and actions that don't save anything.
> Switch to "Save and continue" for all save actions

- app/views/application/confirmation.njk
> content track amend

- app/views/application/confirmation.njk
- app/views/application/edit.njk
- app/views/application/withdraw.njk
- app/views/applications/index.njk
> Content amend/withdraw flow

- app.json
- app/routes/email.js
- app/views/account/check-email.njk
- app/views/account/create-account.njk
- app/views/account/sign-in.njk
- app/views/application/submit.njk
- app/views/email/application-submitted.njk
Send real emails to whitelisted users when:
- signing up
- account created
- signing in
- submitting an application
Followed guidance from:
https://github.com/alphagov/govuk-prototype-kit/blob/bb3592836baad772d9a43cbe6f0b0a9eb5c279e7/docs/documentation/using-notify.md
> Use Notify to send emails

- app/views/account/ineligible.njk
> Content eligibility

- app/views/account/create-account.njk
- app/views/account/eligibility.njk
- app/views/account/ineligible.njk
- app/views/application/before-you-start.njk
- app/views/application/choices/index.njk
- app/views/application/choices/provider.njk
- app/views/apply/index.njk
Content links to participating providers
> Content links to participating providers

- app/views/application/choices/provider.njk
Content tweak to provider link
> Content tweak to provider link

- app/views/application/before-you-start.njk
> Content that way

- app/routes/apply.js
- app/views/apply/providers.njk
- app/views/terms-conditions.njk
Also updates terms and conditions based on latest tweaks.
> Show dual-running variant based on provider

- app/views/applications/index.njk
> Content working days

- app/routes/account.js
- app/views/_includes/item/offer.njk
- app/views/application/decision/accept.njk
- app/views/application/decision/view.njk
- app/views/applications/index.njk
> Content decisions

- app/views/_layout.njk
- app/views/account/create-account.njk
- app/views/privacy-statement.njk
Linked to from create account screen and footer
> Add privacy statement

- app/assets/sass/components/_banner.scss
Now uses same padding and margin values.
> Align banner styles with error summary component

- app/views/application/choices/index.njk
> Show guidance when no course choices

- app/views/application/gcse/grade.njk
- app/views/application/gcse/index.njk
Show specific guidance and grade examples depending on:
a.) Type of qualification (GCSE, GCE O Level or Scottish National 5)
b.) Subject (Maths, English or Science).
Taken directly from the code:
```nunjucks
{% if applicationValue(["gcse", id, "type"]) == "GCSE" %}
{# Available grades:
U,1,2,3,4,5,6,7,8,9 or
U,G,F,E,D,C,C*,B,A,A*
#}
{% if id == "science" %}
{# Maximum number of grades: 3 #}
{% set guidance = "If you have a single, double (also known as combined) or triple GCSE in science, enter your total grade. " %}
{% set hintText = "For example: A*A*A*, AA, B, 999, 88, 7." %}
{% elif id == "english" %}
{% set guidance = "If you have GCSEs in both English Language and English literature, enter your grade for English Language. " %}
{% else %}
{# Maximum number of grades: 1 #}
{% set …
```
> Guidance and hint text for GCSE equivalent grades

- app/views/account/ineligible.njk
- app/views/restricted-access.njk
[Trello card](https://trello.com/c/9sTu3ie6/493-controlled-fall-back-page-pilot-feature-flag)
> Add restricted access page

- app/routes/application.js
- app/views/_includes/review/other-qualifications.njk
- app/views/application/review.njk
Remove unused code, show incomplete state including error state for other qualifications
> Improve review page

- app/views/application/index.njk
- app/views/application/school-experience/index.njk
Amended content so it's clearer that we're asking about all types of volunteering, not just volunteering in a school or with young peopple.
> Content update to volunteering page

- app/views/application/review.njk
- app/views/application/school-experience/review.njk
- app/views/application/school-experience/role.njk
edited content of the review sections of the application form relating to 'volunteering with children and young people' as we've changed the heading of this section to 'unpaid experience and volunteering'
> Content change work history

- app/data/session-data-defaults.js
- app/routes/application/review.js
- app/views/_includes/review/interview.njk
- app/views/application/index.njk
- app/views/application/interview/index.njk
- app/views/application/interview/review.njk
replaced interview preferences with requirements and amended content on interview page followiung university feedback
> changed content in interview requirements section

- app/views/referee-confirmation.njk
https://trello.com/c/aaKMc14Y/800-design-questionnaire-to-get-feedback-from-referees
> Add design for a referee feedback form after giving a reference

- app/views/application/references/alternative-first.njk
- app/views/application/references/alternative-review-2.njk
- app/views/application/references/alternative-second.njk
- app/views/applications/index.njk
- app/views/applications/new-referees.njk
See documentation in https://github.com/DFE-Digital/bat-design-history/pull/53
> Adapt adding new referee pattern to adding 2 referees

- app/views/account/eligibility.njk
- Remove confusing note about EEA (which means Lichtenstein, Norway or Iceland)
- Clarify why we are asking these questions – that it's us that's not ready, rather than them
https://trello.com/c/EOZDqPD7/888-preventing-candidates-getting-blocked-by-the-eligibility-questions
> Updates to eligibility questions

- app/routes/account.js
- app/routes/email.js
- app/routes/reference.js
- app/utils/index.js
- app/views/account/check-email.njk
- app/views/account/index.njk
- app/views/index.njk
- server.js
* Adds a page that asks if you already have an account. If you select ‘yes’, you are prompted to sign in.
* I have kept the existing sign in page. Is there still a need for a separate page? I’m thinking of linking to it directly, either from other points in the journey, or from support tickets.
* Have also moved some generic util functions from `email.js` to `utils.js`.
> Revised sign-in flow

- app/views/application/before-you-start.njk
‘Continue’ because you have already started.
> Use ‘Before you continue‘ as title

- app/views/application/index.njk
- app/views/application/suitability/index.njk
changed content following candidate user research
> declaring any safeguarding issues

- app/views/application/suitability/index.njk
> added link to DBS website

- app/views/application/suitability/index.njk
corrected typo in hint text and fixed spacing under bullets
> minor amends safeguarding page

- app/views/application/index.njk
changed title of this section in the main menu so it matches what we have in the build (we amended title in the build to make it clearer this section is for ALL academic qualifications, not just 'relevant' ones
> academic and other relevant quals

- app/views/application/index.njk
- app/views/application/reasonable-adjustments/index.njk
- app/views/application/reasonable-adjustments/review.njk
- app/views/application/review.njk
- app/views/application/submitted.njk
Updated heading to make it more consistent with crim convictions one.
> Updates to heading

- app/routes/application/choices.js
- app/views/application/choices/another.njk
- app/views/application/choices/index.njk
Prompt users to add another course after they add their first and second courses.
> Add another course flow

- app/routes/apply.js
- app/views/application/choices/find.njk
- app/views/apply/_variant-2020q1.njk
- app/views/apply/index.njk
- app/views/index.njk
Just the plumbing to make the Find interstitial work with three options. Needs *a lot* of refinement and review… even deciding if we want to use this approach.
> Revised Find interstitial

- app/data/session-data-defaults.js
- app/views/_includes/item/reference.njk
- app/views/_includes/review/references.njk
- app/views/application/references/details.njk
- app/views/application/references/index.njk
- app/views/application/references/review.njk
- app/views/application/references/type.njk
> Reinstate reference types with revised content

- app/views/application/suitability/index.njk
content changes following BA research on provider checks
> additional detail on provider checks and what to declare

- app/views/application/references/type.njk
> Corrected typo on reference page

- app/views/reference/safeguarding.njk
> Two questions for referee safeguarding question

- app/data/dummy-application.js
- app/routes/application/other-qualifications.js
- app/views/_includes/item/other-qualification.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/application/other-qualifications/details.njk
- app/views/application/other-qualifications/index.njk
Make it easier to add multiple qualifications of the same type.
> Add another qualification of the same type

- app/views/application/index.njk
Bring prototype inline with live, to make it easier to test Apply 2 things with candidates.
> Add "Incomplete" tags to application index

- app/assets/sass/application.scss
- app/data/previous-applications.js
Forgot to commit previous applications data and remove link to longer needed timeline styles.
🤦🏼‍♂️
> Fix previous applications

- app/views/application/other-qualifications/details.njk
- app/views/application/other-qualifications/index.njk
> Make adding other qualification consistent with other similar multi-entry flows

- app/data/dummy-apply-2-application.js
- app/filters.js
- app/views/_includes/item/reference.njk
- app/views/_includes/review/references.njk
- app/views/application/references/alternative-review-2.njk
- app/views/application/references/alternative-review.njk
- app/views/application/references/review.njk
- app/views/application/review.njk
- app/views/application/submitted.njk
- app/views/applications/index.njk
> Add designs for when a received reference is replaced when making a new application

- app/data/dummy-application.js
- app/data/previous-applications.js
- app/routes/application.js
- app/views/_includes/need-help.njk
- app/views/_includes/review/contact-details.njk
- app/views/_includes/review/gcse.njk
- app/views/_includes/review/interview.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/_includes/review/personal-details.njk
- app/views/_includes/review/personal-statement.njk
- app/views/_includes/review/reasonable-adjustments.njk
- app/views/_includes/review/references.njk
- app/views/_includes/review/subject-knowledge.njk
- app/views/_includes/review/suitability.njk
- app/views/application/contact-details/review.njk
- app/views/application/gcse/review.njk
- app/views/application/index.njk
- app/views/application/interview/review.njk
- app/views/application/personal-details/review.njk
- app/views/application/personal-statement/review.njk
- app/views/application/reasonable-adjustments/review.njk
- app/views/application/references/review.njk
- app/views/application/subject-knowledge/review.njk
- app/views/application/suitability/review.njk
@paulrobertlloyd this PR is increasing in size and taken me a fair amount of work so will do rest of the ticket in separate PR.
Application page:
Individual tasks now have checkboxes:
Review page now reflects those state for each task:
> Apply 2 updates

- app/views/application/index.njk
> Change ‘incomplete’ to ‘in progress’

- app/views/application/index.njk
> Apply2 display reasons

- app/views/application/index.njk
> Change last task into a button

- app/data/degree.js
- app/views/_form-question.njk
- app/views/_includes/item/degree.njk
- app/views/application/choices/pick.njk
- app/views/application/choices/provider.njk
- app/views/application/degree/grade.njk
- app/views/application/degree/index.njk
- app/views/application/degree/institution.njk
- app/views/application/degree/subject.njk
- app/views/application/gcse/index.njk
- app/views/application/other-qualifications/details.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/personal-details/index.njk
* Show undergraduate degree grades for postgraduate degree types
* Allow Level 7 degree types to be selected for first degree (i.e. bachelors and masters, but not doctorates)
* Allow other degree types to be entered
* Improve autosuggest UX
> Structured degrees iteration

- app/data/session-data-defaults.js
- app/routes/application.js
- app/routes/application/contact-details.js
- app/views/_includes/review/contact-details.njk
- app/views/_layout.njk
- app/views/application/contact-details/index.njk
- app/views/application/contact-details/international-address.njk
- app/views/application/contact-details/lookup-address.njk
- app/views/application/contact-details/select-address.njk
- app/views/application/contact-details/uk-address.njk
- app/views/application/contact-details/where-do-you-live.njk
- server.js
* Remove previous `urStudy` mode
* Remove `international_address` feature flag
* Fix international address flow
* Align hint text for telephone number with that used production
* Place editing email address behind `self_amend_email_address` feature flag
> International addresses

- app/data/dummy-application.js
- app/data/session-data-defaults.js
- app/routes/application/personal-details.js
- app/views/_includes/review/personal-details.njk
- app/views/application/index.njk
- app/views/application/personal-details/english-proficiency.njk
- app/views/application/personal-details/index.njk
- app/views/application/personal-details/nationality.njk
- app/views/application/personal-details/residency-status.njk
- app/views/application/personal-details/residency.njk
* Ask nationality on a separate page
* Update residency status question
* Remove ‘Is English your main language?’ question from personal details
* Add ‘Language skills’ section
> 🌐 International: Nationality, residency and language skills

- app/data/dummy-application.js
- app/data/session-data-defaults.js
- app/routes/application/degree.js
- app/routes/application/gcse.js
- app/views/_includes/item/degree.njk
- app/views/_includes/item/gcse.njk
- app/views/_includes/item/other-qualification.njk
- app/views/_includes/review/degrees.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/application/degree/index.njk
- app/views/application/degree/institution.njk
- app/views/application/degree/naric.njk
- app/views/application/degree/subject.njk
- app/views/application/gcse/country.njk
- app/views/application/gcse/index.njk
- app/views/application/gcse/naric.njk
- app/views/application/other-qualifications/details.njk
- app/views/application/other-qualifications/index.njk
* International degree flow
* International standard GCSE flow
* International academic or other relevant qualification flow (including English language qualification)
[Preview these changes here](https://apply-beta-prototype-pr-391.herokuapp.com/application/start)
> 🌐 International qualifications

- app/views/application/degree/naric.njk
- app/views/application/degree/subject.njk
- app/views/application/gcse/naric.njk
- app/views/application/other-qualifications/details.njk
Guidance and content tweaks around international features.
> International tweaks

- app/assets/sass/application.scss
- app/views/_includes/review/personal-details.njk
- app/views/application/index.njk
- app/views/application/personal-details/nationality.njk
Non-functioning prototype for revised nationality question.
> Nationality

- app/routes/application.js
- app/routes/application/review.js
- app/views/application/index.njk
- app/views/application/review.njk
Mock up of closed application and application review pages.
> Closed application page

- app/routes/application/degree.js
- app/routes/application/gcse.js
- app/views/_includes/item/degree.njk
- app/views/_includes/item/gcse.njk
- app/views/application/degree/completed.njk
- app/views/application/degree/grade.njk
- app/views/application/degree/institution.njk
- app/views/application/degree/naric.njk
- app/views/application/degree/subject.njk
- app/views/application/degree/year.njk
- app/views/application/gcse/country.njk
- app/views/application/gcse/grade.njk
- app/views/application/gcse/naric.njk
- app/views/application/gcse/year.njk
- app/views/find/index.njk
* Prototype revised flow for asking if completed degree
* Update to use latest NARIC content
* Bug fixes
> Revised degree grades flow and latest NARIC updates

- app/data/dummy-application.js
- app/data/dummy-decoupled-reference-application.js
- app/routes/account.js
- app/views/_layout.njk
- app/views/account/index.njk
- app/views/application/contact-details/index.njk
- app/views/application/contact-details/review.njk
- app/views/application/english-language/details.njk
- app/views/application/english-language/index.njk
- app/views/application/english-language/review.njk
- app/views/application/english-language/type.njk
- app/views/application/index.njk
- app/views/application/personal-details/index.njk
- app/views/application/personal-details/review.njk
- app/views/application/personal-statement/index.njk
- app/views/application/personal-statement/review.njk
- app/views/application/reasonable-adjustments/index.njk
- app/views/application/reasonable-adjustments/review.njk
- app/views/application/review.njk
- app/views/application/school-experience/index.njk
- app/views/application/school-experience/review.njk
- app/views/application/school-experience/role.njk
- app/views/application/subject-knowledge/index.njk
- app/views/application/subject-knowledge/review.njk
- app/views/application/submitted.njk
- app/views/application/suitability/index.njk
- app/views/application/suitability/review.njk
- app/views/find/index.njk
- app/views/index.njk
* Revised menu structure
* Update EFL section to say assessment instead of qualification
* Update when account links show in header
* Update start page to use new GOV.UK start page
* Tweaks to layout template
> Prototype revised menu structure

- app/routes/reference.js
- app/views/reference/decline.njk
- app/views/reference/thank-you.njk
1. Change content on referee decline page
2. Include radios on referee decline page
3. Create Thank you page
1. Link Yes radio to Thank you page
2. Link No radio to start of the referee flow.
3. i copied the radio code from the Equality and Diversity section - there's still some code about attributes and conditions that refer to equality and diversity - every time I try to take it out I break the page - not getting something right.
4. I've just gone back and changed the apostrophes to curly ones but don' think they've pulled through!
> Content update: decline journey

- app/views/complaints.njk
Will be linked to from a ‘Complaints’ link in the footer.
> Add complaints page

- app/utils/index.js
Opps, I forgot you can't use undefined variables/constants within an `if` condition in javascript... 🤦
> Bugfix: check if notify is defined

- app/views/application/school-experience/index.njk
Update unpaid experience initial question in line with production after a suggestion by the provendor team.
Been meaning to do it since last week - prototype now matches production.
> Update unpaid work initial question

- app/views/_includes/item/other-qualification.njk
> Remove institution from "other qualifications" review section

- app/views/dashboard/_course-choice-conditions.njk
- app/views/dashboard/_course-choices.njk
Offered a different course from the same provider:
Offered a different course from a different provider:
> bugfix: other course offered

- app/views/application/degree/grade.njk
- app/views/application/degree/index.njk
- app/views/application/degree/institution.njk
- app/views/application/other-qualifications/index.njk
...where the user is able to enter free text values. Otherwise some users think that they have to select one of the suggestions.
This has already been done in production.
> Remove "No results found" from autocomplete

- app/utils/index.js
The structure of these sections was updated as part of some refactoring work. (eg 8f01913620d8c9c0a7522459d3348ede6d12d9f4).
> Update keys to check for completed status

- app/views/survey/index.njk
Changed "How satisfied are you" to optional 
and "Send feedback" button to "Continue"
> Small tweaks to survey page

- app/routes/application/gcse.js
- app/views/_includes/item/gcse.njk
- app/views/_includes/review/gcse.njk
- app/views/application/gcse/grade.njk
- app/views/application/gcse/no-pass-grade.njk
Ask an extra question if GCSE grade is lower than 4 (C)
> Ask how a candidate meets minimum GCSE requirement

- app/views/application/personal-information/residency.njk
Missing full stop in first sentence.
> Correct full stop

- app/data/application.js
This restored the GCSE and degree entries, plus adds A levels for the "completed application" state.
> Fix completed (dummy) application

- app/views/_includes/review/unpaid-experience.njk
- app/views/application/references/start.njk
- app/views/index.njk
Add links to Get Into Teaching on:
* [Service start page](https://apply-beta-p-git-links-tbcnqjc.herokuapp.com)
* [Requesting references start page](https://apply-beta-p-git-links-tbcnqjc.herokuapp.com/application/12345/references/add)
* [Prompt on Unpaid experience review page](https://apply-beta-p-git-links-tbcnqjc.herokuapp.com/application/12345/unpaid-experience/review)
> Add links to Get Into Teaching

- app/data/application.js
This was throwing an error at the application review step.
> Bugfix: missing line2 value in address

- app/views/application/equality-monitoring/disabilities.njk
- app/views/application/equality-monitoring/disability-status.njk
- app/views/application/equality-monitoring/ethnic-background.njk
- app/views/application/equality-monitoring/ethnic-group.njk
- app/views/application/equality-monitoring/index.njk
- app/views/application/equality-monitoring/religious-belief.njk
- app/views/application/equality-monitoring/review.njk
- app/views/application/equality-monitoring/sex.njk
- app/views/application/equality-monitoring/sexual-orientation.njk
To bring the prototype inline with QA:
- update start question to 'Do you want to answer a few questions about your sex, disability and ethnicity?'
- update start question answers
- remove 'continue to the questionnaire' from the Yes answer
- remove 'continue without completing questionnaire' from the No answer
- add 'Prefer not to say option' to:
- disability status
- sex
- update page caption to 'Equality and diversity questionnaire'
- remove parentheses `()` from hint text
> Update equality and diversity questionnaire

- app/assets/javascripts/application.js
- app/assets/javascripts/modules.js
- app/assets/javascripts/modules/clear-hidden.js
- app/assets/javascripts/modules/feedback.js
This is broken in a way I don't understand yet.
> Comment out broken 'modules' code

- app/views/application/index.njk
- app/views/application/references/name.njk
- app/views/application/references/relationship.njk
- app/views/application/references/review.njk
- app/views/application/references/type.njk
- app/views/reference/comments.njk
- app/views/reference/relationship.njk
A few copy changes following initial peer review
> copy tweaks

- app/views/application/references/review.njk
- app/views/application/references/start.njk
- app/views/reference/comments.njk
> Re order bullet list

- app/filters.js
- app/views/_document.njk
- app/views/_includes/review/unpaid-experience.njk
- lib/utils.js
- package.json
We're no longer using markdown in the prototype at all.
> Remove markdown renderer

- app/assets/javascripts/sort.js
Applies fixes from https://github.com/DFE-Digital/register-trainee-teachers/pull/1697
> autocomplete synonym fixes

- lib/utils.js
> Remove marked reference

- app/views/application/decision/accept.html
- app/views/application/decision/view.html
Bringing this up-to-date with the content from production (removing UCAS references and repeated information on confirmation page)
> Update accept offer flow

- app/views/_includes/review/subject-knowledge.html
- app/views/application/personal-statement/index.html
- app/views/application/personal-statement/review.html
- app/views/application/subject-knowledge/index.html
Brings the content in these 2 sections up-to-date with production.
> Update content in personal statement sections

- app/views/_includes/item/choice.html
- app/views/application/personal-information/visa-route.html
This is in response to feedback from Becky Jones.
> Make it clear that courses or providers don't sponsor visas

- app/views/_includes/item/choice.html
- app/views/application/personal-information/visa-route.html
it's not always the provider that sponsors visas, so for simplicity and to avoid inaccuracy, change to more generic copy
> policy feedback changes

- app/assets/javascripts/sort.js
Not sure how this got deleted...
> Re-instate sort.js

- .github/workflows/lint.yml
- app/assets/javascripts/sort.js
- package-lock.json
- package.json
This runs the javascript linting in auto-fix mode on all github pull requests, and then commits and pushes any fixes.
> Add auto-linting

- package-lock.json
Required by yargs.
Aims to resolve deploy issue:
```
Missing: which-module@1.0.0 from lock file
```
> Downgrade which-module to version 1.0.0

- app/routes/application/equality-monitoring.js
- app/views/_includes/review-equality-monitoring.html
- app/views/application/equality-monitoring/free-school-meals.html
- app/views/application/equality-monitoring/household-earner-occupation-at-14.html
This is an exploration of how we might add the "key question" [proposed by the social mobility commission](https://socialmobilityworks.org/toolkit/measurement/) to measure social-economic background.
> Add question: What was the occupation of your main household earner when you were about aged 14?

- app/views/application/references/index.html
This is consistent with other sections, and gives more room for content.
> Make references summary cards full-width

- app/views/dashboard/_guidance.html
Couple of content tweaks we spotted.
> Tweak content

- app/views/_includes/item/reference.html
- app/views/application/references/type.html
- app/views/dashboard/references/type.html
We updated this content slightly when implementing it in production.
> Tweak content to match production

- package-lock.json
- package.json
Latest version seems to break the app
> Downgrade inquirer to version 8

- app/views/application/additional-support/index.html
- app/views/application/choices/find.html
- app/views/application/decision/view.html
- app/views/application/degree/review.html
- app/views/application/gcse/equivalency.html
- app/views/application/subject-knowledge/index.html
- app/views/dashboard/_apply-again.html
- app/views/dashboard/index.html
Get Into Teaching have asked us to update some content and links from various places on the prototype.
Trello ticket: https://trello.com/c/06Nbw6Sg/1011-go-through-and-add-link-from-apply-to-git
> changed content in line with GIT recommendations

- app/views/_includes/item/choice.html
- app/views/dashboard/_course-choices.html
Small content change to match changes made about deferrals on production.
Trello ticket: https://trello.com/c/lIsLoOXQ/1003-review-our-offer-emails-to-try-and-remove-encouragement-for-deferrals
> content to match production

- package-lock.json
- package.json
> Upgrade filters plugin

- app/assets/sass/components/_primary-navigation.scss
- app/routes.js
- app/views/_components/primary-navigation/template.njk
- app/views/layouts/main.html
This adds the sign out button to the right hand side of the navigation bar, using CSS code borrowed from [the implementation in production](https://github.com/DFE-Digital/apply-for-teacher-training/pull/8311).
> Add sign out button to navigation bar

- app/routes/details/references.js
When selecting the reference link for the task list, the first thing you see was an error. This code corrects that.
Error:
> Fixed references error

- app/routes.js
- app/routes/details/degree.js
- app/routes/details/gcse.js
- app/routes/details/other-qualifications.js
- app/routes/details/references.js
- app/routes/details/safeguarding.js
- app/routes/details/unpaid-experience.js
- app/routes/details/work-history.js
- app/views/_includes/item/degrees.html
- app/views/_includes/item/gcse.html
- app/views/_includes/item/job.html
- app/views/_includes/item/other-qualifications.html
- app/views/_includes/item/reference.html
- app/views/_includes/item/unpaid-experiences.html
- app/views/_includes/item/work-history.html
- app/views/_includes/review/other-qualifications.html
- app/views/_includes/review/safeguarding.html
- app/views/details/degree/review.html
- app/views/details/gcse/review.html
- app/views/details/index.html
- app/views/details/other-qualifications/review.html
- app/views/details/references/index.html
- app/views/details/safeguarding/index.html
- app/views/details/safeguarding/review.html
- app/views/details/unpaid-experience/review.html
- app/views/details/work-history/review.html
https://trello.com/c/zgdjm6SQ/340-apply-add-designs-for-editing-information-after-submission-in-apply-prototype
Also, fixed the 'complete/incomplete' tags
> Add designs for editing information after submission in Apply prototype

- app/routes.js
- app/routes/applications.js
- app/routes/details/personal-statement.js
- app/views/_includes/review/personal-statement.html
- app/views/applications/course.html
- app/views/applications/index.html
- app/views/applications/review-application.html
- app/views/applications/review.html
- app/views/details/index.html
- app/views/details/personal-statement/index.html
- app/views/details/personal-statement/review.html
Added back personal statement to the 'your details' page. 
And added an inset text on the personal statement review page when atleast 1 application is submitted.
> Adding back personal statement

- app/views/applications/index.html
- app/views/applications/review.html
- app/views/details/index.html
- app/views/details/personal-information/immigration.html
- Added a green button with a box to navigate to 'applications' once all 'your details' sections are completed.
- Added a link at the top of 'your details' page to navigate to 'applications' + amended some content on details being shared with the provider.
- Added a link to navigate back to 'your details' from applications if the details are not completed.
- Added a link in 'review application' if the details are not completed  back to 'your details' + content about application being saved as a draft.
> Navigation

- app/views/details/index.html
The below used to say "You can now start applying to courses."
> Changed text to help users navigate

- app/routes.js
- app/routes/applications.js
- app/views/applications/review.html
- app/views/applications/school-placement-preferences.html
- app/views/applications/school-placement.html
- app/views/details/degree/review.html
- app/views/details/gcse/grade.html
- app/views/details/index.html
- app/views/details/other-qualifications/review.html
- app/views/details/safeguarding/review.html
- app/views/layouts/main.html
- app/views/manage-prototype-data/view-data.html
School placements:
* Allow select two preferred placement schools
* New placement preference questions
Bug fixes:
* Issues preventing sections being marked as complete.
* Radio group without name allowing multiple selection
> School placements

- app/routes/applications.js
> Updates from review

- app/filters.js
- app/routes/applications.js
- app/views/_components/application-status/macro.njk
- app/views/_components/application-status/template.njk
- app/views/applications/index.html
- app/views/applications/review-application.html
- app/views/applications/withdraw-reason.html
- app/views/applications/withdraw.html
- package-lock.json
We have some upcoming work to update the reasons providers can select when rejecting an application.
This PR is to update the prototype to reflect the current journey on live, as it was quite different.
> Updating candidate withdrawal reasons

- app/routes/applications.js
- app/views/_components/application-status/macro.njk
- app/views/_components/offer-summary/macro.njk
- app/views/_components/offer-summary/template.njk
- app/views/applications/decline-confirm.html
- app/views/applications/index.html
- app/views/applications/respond.html
- app/views/applications/review-application.html
Making consistent with QA.
* Adding summary section
* Adding confirmation screen
* Adding success banner
> Updating decline offer journey

- app/routes/reference.js
- app/views/reference/index.html
- app/views/reference/share.html
Only show confidential question if they say they can provide a reference.
> Reference flow fix

- app/routes/applications.js
- app/views/applications/candidate-pool.html
- app/views/applications/index.html
- app/views/applications/interruption-module.html
Giving candidates the option of allowing other providers to view their application and invite them to apply.
> Adding candidate pool opt in

- app/assets/sass/application.scss
- app/routes/accepted.js
- app/routes/applications.js
- app/routes/details/references.js
- app/views/_components/application-status/template.njk
- app/views/accepted/index.html
- app/views/accepted/references/action.html
- app/views/applications/index.html
Removing out of date designs to ensure consistency with prod for testing.
> Alignments to prod

- app/routes/applications.js
Ensure it shows content based on correct number of remaining application slots after opting in/out of FAC.
> Fixing bug

- app/routes/applications.js
- app/views/applications/delete.html
- app/views/applications/review-application.html
Adding review page variation for draft applications
> Proto fixes

- app/assets/sass/application.scss
- app/assets/sass/components/_phase-banner.scss
- app/views/layouts/main.html
- package-lock.json
- package.json
Updating to use onelogin header
> Header updates

- app/routes/applications.js
Temporary fix to facilitate May test session. Can be removed later
> Temp location fix

- app/routes/admin.js
- app/routes/applications.js
- app/views/applications/index.html
- app/views/candidate-pool/check.html
- app/views/candidate-pool/index.html
- app/views/candidate-pool/info.html
- app/views/candidate-pool/locations/add.html
- app/views/candidate-pool/locations/areas.html
- app/views/candidate-pool/locations/auto-add.html
- app/views/candidate-pool/locations/change.html
- app/views/candidate-pool/locations/index.html
- app/views/candidate-pool/locations/remove.html
- app/views/layouts/main.html
> FAC opt in updates

- app/routes/applications.js
- app/views/candidate-pool/check.html
- app/views/candidate-pool/locations/auto-add.html
Skip auto add page if no location preference
Change yes/no radios to inline on auto-add page
> FAC tweaks
