DFE-Digital/apply-for-teacher-training-prototype

- app/views/_form.njk
- app/views/account/create-account.njk
- app/views/email/confirm-address.njk
Don't automatically use legends: For the sake of the prototype, use headings which get given the correct spacing between titles and subsequent labels and fields.
- Match design system for email field (https://design-system.service.gov.uk/patterns/email-addresses/)
- Add a back link
- Revert title to before you begin (save and return felt like a page had been missed in the process)
> Tweak form layout and asking for email

- app/assets/javascripts/application.js
- app/assets/javascripts/modules.js
- app/assets/javascripts/modules/edge.js
- app/views/_includes/scripts.njk
- app/views/_layout.njk
- Use a `data-module` pattern to invoke JS modules
- Add an edge module to warn if a user clicks a link that doesn't go anywhere
> Import modules from Manage prototype

- app/data/session-data-defaults.js
- app/routes/gcse.js
- app/views/_includes/review-gcse.njk
- app/views/application/gcse/grade.njk
- app/views/application/gcse/index.njk
- app/views/application/gcse/review.njk
- app/views/application/gcse/year.njk
- app/views/application/index.njk
- app/views/application/review.njk
* Adds review your answers step after entering a GCSE or equivalent
* Updates GCSE review include to use `summary` component, showing just one qualification (which is included in a loop on application review page)
> Add review step for GCSE qualifications

- app/routes/application/personal-details.js
- app/views/_includes/review-personal-details.njk
* Fixes review page not appearing after entering personal details
* Fixes flow so that whenever you enter a non-EEA nationality, you are asked for residency status
* Fixes submitted data such that if you enter a non-EEA nationality and residency status answer, but then change back to a EEA nationality, residency status answer is removed (and thus not shown on application)
> Fix personal details review flows

- app/assets/sass/components/_autocomplete.scss
Relates to https://github.com/alphagov/accessible-autocomplete/issues/202
This isn't an ideal fix but is fine for prototyping.
> Make autocomplete arrow clickable

- app/routes/application.js
- app/views/application/confirmation.njk
- app/views/email/application-submitted.njk
- Secretly link to it from confirmation page
- List courses applied to
- Link back to the Applications page to see status
Content will be looked at separately by @laurahermionetennant92, words based on initial version we tried on Find in March.
> Create an application submitted email

- app/data/session-data-defaults.js
- app/routes/application.js
- app/views/_layout.njk
- app/views/application/contact-details/index.njk
- app/views/applications/index.njk
- app/views/index.njk
- Value of `UR_STUDY` is now used as application ID (if exists)
- Update routes so that if `UR_STUDY`, use that to create new application ID
- Update landing page with different calls to action if user study, and if user is returning
- Update landing page with notice for candidates to record their session
- Fix ‘Clear data’ link in footer
> Tweaks for user research instance

- app/views/index.njk
The start method sets up the objects we need to attach things like courses to. Without going through this you can't add courses to an application.
https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/blob/master/app/routes/application.js#L3-L13
> Link to `/application/start` rather than `/application/CODE`

- server.js
The default of 1 was creating a strange behaviour.
Instead, only default the session ID if urStudy is provided and urStudy is a string.
https://github.com/expressjs/session#genid
> Function to call to generate a new session ID. Provide a function that returns a string
> When making sessions, `genid` must always return a string

- app/views/_includes/review-personal-statement.njk
- app/views/application/personal-statement/review.njk
- app/views/application/review.njk
Previously we were using `statement.id` to link to the statement forms, but on the application section this was undefined, meaning the values were being added to the wrong place.
Use statementId consistently, using the Nunjucks way of looping through an object’s keys and values.
Fixes #171
Caused by 2c863729cc536cdc3fa8200b3e76043885114cc2
> Show personal statements when entered

- app/views/_includes/review-equality-monitoring.njk
- app/views/application/equality-monitoring/disability-status.njk
- app/views/application/equality-monitoring/sex.njk
- Remove ‘Prefer not to say’ on disability and sex equality monitoring questions
- Fix `the return value of (applicationValue)["includes"]` error on  equality monitoring review page
- Fix logic around display of ethic backgrounds w/r/t ‘Prefer not to say’ for group/background.
Fixes #178.
> Prefer not to say

- app/data/session-data-defaults.js
- app/views/_includes/review/work-history.njk
- app/views/application/work-history/explain-gaps.njk
- app/views/application/work-history/index.njk
- app/views/application/work-history/review.njk
* Adds `automatic_gaps` feature flag and sets it to `false`.
* If `true`, gaps longer 1 month appear in work history, with option for candidate to provide explanation for each
* If `false`:
* Removes “More than 5 years, but with gaps” option from work history introduction page 
* Removes display of automatic gaps in work history
* Provides a summary card after last item in work history with the option to add reasons for any gaps
* This links to a new page “Explain gaps in work history”.
> Add feature flag for automatic gaps in work history

- app/routes.js
- app/routes/remove.js
- app/utils/index.js
- app/views/_includes/item/gap.njk
- app/views/_includes/item/job.njk
- app/views/_includes/review/degrees.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/_includes/review/references.njk
- app/views/_includes/review/school-experience.njk
- app/views/_includes/review/work-history.njk
- app/views/application/remove.njk
- Links remove links on summary cards to remove page
- Adds a review page
- Adds `get` route for removing items, that shows a confirmation page
- Adds `post` route for removing items, that deletes item object from session data
- Fixes a few things in work history around gaps/jobs (titles and an incorrect links)
Fixes #150.
**NOTE: This PR does not include removing courses. That’s gunna be a bit more involved.**
> Deleting data

- app/assets/sass/application.scss
- app/assets/sass/components/_course.scss
- app/assets/sass/components/_summary-card.scss
- app/assets/sass/components/_task-list.scss
Updates styles to remove unnecessary links, buttons and navigation elements appearing when pages are printed. Beyond being suggested changes for the service, in the meantime these changes will allow us to create usable PDF version of any applications submitted via the prototype.
> Print styles

- app/config.js
- app/views/_email.njk
- app/views/email/application-submitted.njk
- app/views/email/confirm-address.njk
- app/views/index.njk
- package.json
- server.js
- Changes service name to ‘Apply for teacher training’ (for user research)
- Makes the service URL (slug) configurable
- Updates emails to include service name/slug variables
> Use shorter name, and add (more) placeholders for service name and slug

- app/filters.js
- app/views/_includes/item/gap.njk
- app/views/_includes/review/work-history.njk
- Don’t use `toArray` filter twice (causes `item.id` to return array index instead of ID)
- Ensure UNIX epochs are returned as numbers before comparing
> Work history bugs

- app/assets/sass/application.scss
- app/assets/sass/components/_caption.scss
- app/assets/sass/components/_heading.scss
- app/assets/sass/components/_summary-card.scss
- app/assets/sass/components/_table.scss
- app/routes/delete.js
- app/views/_components/icon/template.njk
- app/views/_includes/item/job.njk
- app/views/_includes/item/role.njk
- app/views/_includes/review/school-experience.njk
- app/views/_includes/review/work-history.njk
- app/views/application/school-experience/role.njk
- app/views/application/work-history/job.njk
- Adds additional fields to volunteering role
- Moves indication for jobs/roles that involved working with children to summary card title
- Stacks and renames action links on gap card (Fixes #205)
- Removes deprecated app styles (`app-caption`, `app-heading` and `app-table__row--muted`)
- Remove day from role start and end dates
> Various fixes and improvements for work and volunteering

- app/assets/javascripts/modules/clear-hidden.js
- app/data/session-data-defaults.js
- app/routes/application/school-experience.js
- app/routes/application/work-history.js
- app/utils/index.js
- app/views/_components/footer/template.njk
- app/views/_content-wide.njk
- app/views/_content.njk
- app/views/_form-wide.njk
- app/views/_form.njk
- app/views/_includes/item/gap.njk
- app/views/_includes/item/job.njk
- app/views/_includes/item/role.njk
- app/views/_includes/review/degrees.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/_includes/review/references.njk
- app/views/_includes/review/school-experience.njk
- app/views/_includes/review/work-history.njk
- app/views/_layout.njk
- app/views/application/index.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/other-qualifications/review.njk
- app/views/application/review.njk
- app/views/application/school-experience/role.njk
- app/views/application/work-history/job.njk
- app/views/application/work-history/review.njk
- Adds ‘Add another {thing}’ when adding a new job/school experience/other qualification
- Button doesn’t show if you decide to add another from the review page
- Button doesn’t show if you are editing an existing item
- Update routes for work history and school experience so that we convert date components when posting to `/review` or `/add/:type`, instead of directing to an `/update` page. Required for the above change
- `saveIsoDate` now saves an end date as `now` if no date is provided, removing the need to do that in templates. Also adds a bit of error handling, skipping this function if no `id` is provided
- Normalises spacing below page heading across layouts
- Fixes reviewing an application when no data has been entered
> Add or continue

- app/routes/application.js
- app/routes/application/degree.js
- app/routes/application/school-experience.js
- app/routes/application/work-history.js
- app/views/_includes/item/degree.njk
- app/views/_includes/item/gap.njk
- app/views/_includes/item/gcse.njk
- app/views/_includes/item/job.njk
- app/views/_includes/item/role.njk
- app/views/_includes/review/degrees.njk
- app/views/_includes/review/work-history.njk
- Ensures any radio questions that have follow on branching logic, a non-answer doesn’t break the prototype or send user in a loop
- Ensure job and role dates are still updated as ISO 8601 if editing from application review page
- Fixes job/role form action to return to referring page (if provided)
- Fixes a cases of ‘Not entered’ not appearing if no data entered for a question
> Safe fallbacks for now answered branches

- app/views/account/check-email.njk
- app/views/email/confirm-address.njk
Updates to magic link email content. See [Card 73](https://trello.com/c/xBMMWn5J). @laurahermionetennant92 to review.
> ### Please confirm your email address
> Click the link below to confirm your email address and go back to the **Apply for teacher training** service.
>
> [[Link]](#)
>
> You will then be able to save and return to your application.
>
> By signing in, you also agree to the [terms and conditions](#) of the ‘Apply for teacher training’ service.
> ### Sign in to Apply for teacher training
>
> Click the link below to sign in to the **Apply for teacher training** service.
>
> [[Link]](#)
> ### Please confirm your new email address
>
> Click the link below to confirm your new email address and go back to the **Apply for teacher training** service.
>
> [[Link]](#)
> Update magic link email content

- app/data/session-data-defaults.js
- app/utils/filters-with-app-context.js
- app/views/application/other-qualifications/index.njk
Allow applications to reuse school, year and qualification type when they add another qualification.
Prefills:
- Type of qualification
- Name of school
- In UK/out of UK
- Country if provided
- Year
Does't prefill:
- Subject
- Grade
> Prefill qualifications based on earlier values

- app/views/application/choices/pick.njk
- keep full list of providers so candidates can always find who they’re looking for
- if a provider who isn’t in pilot is picked, give a route to UCAS, maybe some guidance, maybe a link to the dual running page on GiT
> Stub "Apply on UCAS" page in course flow

- app/assets/sass/components/_related.scss
- app/routes.js
- app/routes/account.js
- app/routes/apply.js
- app/views/_components/related/template.njk
- app/views/_guidance.njk
- app/views/account/create-account.njk
- app/views/account/eligibility.njk
- app/views/account/ineligible.njk
- app/views/application/choices/pick.njk
- app/views/apply/index.njk
- app/views/index.njk
- Moves pilot eligibility questions so that they appear after the ‘Start now’ action from the service landing page. This is so that we can shift candidates regardless of their route in.
- Interstitial from Find is now a simple choice between the respective Apply and UCAS URLs (if course/provider is opted in).
`/account/eligibility`
`/account/ineligible`
- The content on the ineligible page needs review. Is providing links to related content in a sidebar the right approach. Are those the right links?
- If you are eligible, is ‘Before you start’ still the right title for the following page?
- Should the page we show when choosing a non-opted on course align more closely with this design (i.e. with the sidebar links)?
- When we add carrying over course details from Find, we should also …
> Move pilot eligibility questions to cover all routes in

- app/routes/application.js
- app/routes/application/choices.js
- app/views/application/choices/find.njk
- app/views/application/choices/found.njk
- app/views/application/choices/index.njk
- app/views/application/choices/pick.njk
We want users to add a course straight away, or fail fast – ie leave for UCAS if we can't accommodate their choice.
We don't want to risk users completing an application form, then not being able to apply to the course they want to.
Introduces concept of a welcome flow.
> Send users straight into the add course flow

- app/routes/email.js
- app/views/account/account-created.njk
- app/views/account/check-email.njk
- app/views/account/create-account.njk
- app/views/email/application-submitted.njk
- app/views/email/confirm-address.njk
- app/views/email/welcome.njk
Users are not sure that they've created an account, and are unsure how to return.
Include an explicit confirmation step.
Part of https://trello.com/c/dgQjwXb2/220-save-and-return
> Add an account created page

- app/views/_layout.njk
Shows links to the different variants in the footer for those pages which include `providerCode` and `courseCode` variables to a template (i.e. pages in the dual running and course selection journeys).
> Add Apply variant links

- app/data/session-data-defaults.js
- app/routes/application/contact-details.js
- app/views/_includes/need-help.njk
- app/views/_includes/review/contact-details.njk
- app/views/application/contact-details/review.njk
- app/views/application/edit.njk
- app/views/application/references/review.njk
- app/views/application/review.njk
- app/views/application/submitted.njk
- app/views/applications/index.njk
As a general point, I think we should show the ability to edit your contact details regardless of application phase, i.e. even during the amendment period. Thought being, if someone wants to edit their address, doing so shouldn’t mean they then lose the ability to resubmit an edited application should they then wish to make further changes (within the amendment period).
We include an email link in the sidebar:
We show your contact details at the bottom of the page, and allow you to edit fields individually. This essentially works the same as it does when completing your application. Nice!
> Editing contact details at any time

- app/assets/sass/components/_banner.scss
- app/data/dummy-application.js
- app/data/session-data-defaults.js
- app/routes/application.js
- app/routes/application/degree.js
- app/routes/application/gcse.js
- app/routes/application/personal-details.js
- app/routes/application/review.js
- app/utils/index.js
- app/views/_components/banner/template.njk
- app/views/_includes/review/choices.njk
- app/views/_includes/review/contact-details.njk
- app/views/_includes/review/degrees.njk
- app/views/_includes/review/gcse.njk
- app/views/_includes/review/incomplete.njk
- app/views/_includes/review/interview.njk
- app/views/_includes/review/personal-details.njk
- app/views/_includes/review/personal-statement.njk
- app/views/_includes/review/reasonable-adjustments.njk
- app/views/_includes/review/references.njk
- app/views/_includes/review/school-experience.njk
- app/views/_includes/review/subject-knowledge.njk
- app/views/_includes/review/work-history.njk
- app/views/application/degree/review.njk
- app/views/application/index.njk
- app/views/application/review.njk
- app/views/application/school-experience/index.njk
- app/views/application/submitted.njk
- app/views/application/work-history/index.njk
* Fixes review page not being viewable
* Fixes review page not being submittable
* Fixes issue where trying to complete an incomplete GCSE or Degree from the review page, wouldn’t allow you to answer the follow on questions about year, grade etc (`referrer` took precedence. Now only directs to referrer if grade and year already have values).
* Updates CSS and markup for banner component to match that used on line service (including ability to display an icon)
* Uses banner component to show blue/red incomplete warnings on review page (better reflecting component used on live service)
* Updates section review includes to display new incomplete banners
* Updates incomplete messages to match those used on live service
* Updates routes for review pages to validate every section (and moves …
> Refactor reviewing and submitting incomplete application

- app/utils/index.js
- app/views/application/submit.njk
Prior to testing the training with a disability question, removing the ‘catch-all’ question that appears on the submit page, as this currently serves much of the same purpose. There are additional questions surrounding DBS checks, but those can be dealt with separately/later.
Updated page:
> Remove last catch-all question

- app/views/application/work-history/job.njk
changed first sentence to 'Please include all your paid work in this section' to match live version. we changed this as it wasn't clear that we want to know about all paid work, as opposed to just paid work in a school
> content change work history first sentence

- app/routes/application.js
- app/routes/application/suitability.js
- app/views/_includes/review/suitability.njk
- app/views/application/index.njk
- app/views/application/review.njk
- app/views/application/suitability/index.njk
- app/views/application/suitability/review.njk
- Add section in personal details
- Model on disability section, making disclosure optional and encouraging conversation with providers
- Add a completed badge and show on final review
- Content from https://docs.google.com/document/d/1tpCtUbjjL5BBakBAaKEgawXHroUu4-YVU46e57dUM2w/edit
Im not sure what text we should use when the section hasn't been completed, no information entered is different to no decision made.
https://trello.com/c/hkMU3bDS/744-re-evaluate-designs-for-criminal-conviction-declarations-feedback-from-providers
Universities have given us some "red flag" feedback that we are not doing enough to capture information about criminal convictions in our application form:
> A section for convictions or cautions? In regards to safeguarding and sex offences. They think it is good …
> Add section for suitability to work with children

- app/views/application/references/alternative-review.njk
- app/views/application/references/alternative.njk
- app/views/applications/index.njk
- app/views/applications/new-referee.njk
Design outlined below.
What's missing:
- Updates to the emails we send out
Journeys:
```
Email asking for new referee > Click link > Sign in > Click sign in link > See ask for new details page
```
```
Homepage > Sign in > Click sign in link > See ask for new details page
```
- Show this page instead of the default home page
- Give reason why they need to replace referee, matching words used in emails
- Allow users to skip the step
- Same as referee form with minor changes
- Removes hint text about when we will contact them
- Has a descriptive title that matches button used to reach here (and no caption)
- Because the action is immediate, we will automatically email new referee, we need a review step
- Give the candidate a chance to catch any errors
- Confirming will send email and return …
> Design for adding a replacement referee

- app/views/index.njk
We’ll review the need for including this guidance when we reintroduce these sections, but thinking is we don’t need to include this guidance here, at this point in the journey.
> Hide disability and criminal convictions guidance from start page

- app/views/account/index.njk
We should privilege new users over returning users on this page.
> Update title for account page

- app/views/application/before-you-start.njk
@emmajhf Me and @fofr played around with this page to make it less wordy and put the emphasis on the one message we want users to take away from this page, that we recommend that they choose a course first. Thoughts?
> Alternative content for before you continue page

- app/routes/application/choices.js
- app/views/application/choices/pick.njk
- app/views/apply/index.njk
Updates the design of the page that candidates see if they select a course that’s not on Apply (within the Apply ‘choose a course’ journey). We may need to tweak the content to reassure candidates that they can use both services (picking three courses across both) if they so wish. /cc @emmajhf
> Update content on UCAS apply pages

- app/views/_includes/item/gcse.njk
- app/views/application/gcse/grade.njk
- package.json
For GCSE or equivalent grades, include guidance around minimum grade and suggestion to contact a provider if currently don‘t meet the criteria.
* * *
For English GCSE subject, add two disclosures:
1. Only have an English Literature qualification
2. Have more than one English qualification
> Additional guidance for GCSE grades

- app/data/gcse-subjects.js
- app/data/session-data-defaults.js
- app/routes/application/other-qualifications.js
- app/views/_includes/item/other-qualification.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/application/other-qualifications/details.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/other-qualifications/review.njk
- server.js
First pass at prompting for a qualification type (GCSE, A Level, AS Level, Other) within the other qualifications section.
Also includes support for entering structured subjects for GCSE qualifications. This aspect may need more work (ie do we show pilot qualifications, do we merge qualifications with similar subject titles, etc). These issues can be addressed later, in a separate PR.
> Structured other qualifications

- app/data/dummy-application.js
- app/data/dummy-apply-2-application.js
- app/data/session-data-defaults.js
- app/routes/application.js
- Include an "apply2" boolean for each application, which we can use to toggle Apply2 specific features (eg limit that application to 1 course choice)
- Create an apply2 dummy application derived from the existing dummy
- Add a route for copying an existing application and making it into a new Apply 2 one
- Add missing suitability fields to defaults and dummy applications
> Allow creation of Apply 2 applications

- app/data/dummy-apply-2-application.js
- app/routes/application.js
- app/routes/application/choices.js
- app/routes/application/review.js
- app/views/_includes/item/reference.njk
- app/views/_includes/need-help.njk
- app/views/_includes/review/references.njk
- app/views/application/apply-again.njk
- app/views/application/choices/index.njk
- app/views/application/index.njk
- app/views/application/review.njk
- app/views/applications/index.njk
For review:
- This PR mostly focuses on the logic/mechanics.
- Much of the content here is placeholder
- Pages and banners have content that is there as a good starting point
Changes:
- Course choices becomes Course choice
- 3 choices becomes 1 choice in guidance
- Remove add another course flow and button
- Add an apply again page, link to it from the dashboard
- Show a copied banner when a new application is made
- Tweak Apply 2 application title to be "Your new application"
- Suggested placement for link to previous applications
- Show reference statuses on an Apply 2 application
- Make references read only (you can replace or delete but not change aspects of)
> First pass at tweaks to the application for Apply 2

- app/views/application/apply-again.njk
We've replaced the phrase 'was not successful' to cover all scenarios.
> Update content on interstitial for Apply 2

- app/views/apply/providers.njk
* `eastern` `region_code` to use title ‘East of England’
* If no providers in a region, still show it, but say ‘No providers are available in this region yet.’
* Use ‘No region’ as heading for providers without a `region_code`
> Group list of providers by region

- app/views/application/degree/grade.njk
- app/views/application/degree/institution.njk
- app/views/application/degree/subject.njk
…and provide autosuggest for ‘Other’ option:
We’re pretty confident these are the only other options, but don’t want to prevent candidates who may want to provide a different answer from completing this question.
> Reduce number of undergraduate degree grade options

- app/data/dummy-application.js
- app/data/dummy-apply-2-application.js
- app/routes/application.js
- app/views/application/index.njk
This is just one of the changes that came out of Apply 2 actions; I’m doing this now as the ‘In progress’ tags may cause issues for international UR which follows the Apply 1 journey.
* Changes ‘In progress’ to ‘Incomplete’ (across both Apply 1 & 2)
* Changes incomplete tag to grey
* Mark all sections as completed (except for course choices) when copying an application for Apply 2
> Apply 2: Revert status tags

- app/data/session-data-defaults.js
- app/routes/application/decision.js
- app/routes/email.js
- app/views/application/decision/withdraw-confirmation.njk
- app/views/application/decision/withdraw.njk
After you withdraw, now show a confirmation screen, which asks 2 questions:
* Do you have a reason for withdrawing?
* Can we contact you about your experience of withdrawing?
We make it clear that feedback will only be shared with the Department for Education, and reinforce this again if candidate selects ‘Yes’ to the first question.  
Selection ‘Yes’ to either, show the following free text areas:
> Reason for withdrawal

- app/routes/application.js
- app/views/_content.njk
- app/views/application/apply-again.njk
- app/views/application/before-you-start.njk
There’s a gap in the current design for apply 2 in that users make a copy of their application before choosing a course. This means that someone could do this, start amending bits of their application, and then choose a course only to realise it’s on UCAS.
After applying again, take users to the "We suggest you choose a course first" page rather than their application. This is consistent with their first application.
Also:
- Update language to avoid "copying", instead infer more of a continuation
- Be more aspirational on the interstitial
https://trello.com/c/fiQBqrbp/1404-apply-2-initial-flow-choosing-a-course
> Suggest candidates choose a course first when applying again

- app/views/application/decision/accept.njk
- app/views/application/decision/decline.njk
- app/views/application/decision/withdraw.njk
“Are you sure you want to accept offer” contained guidance on withdrawing other choices that’s not relevant when applying again (there’s only 1 choice).
“Are you sure you want to decline offer” contains guidance about applying again through UCAS, when this feature is launched apply again will not be specific to UCAS.
The updated content removes mention of:
- UCAS when suggesting a candidate can apply again after declining
- the caveat about “all other offers” when declining an offer on an application with 1 choice
- automatically withdrawing other choices when accepting an offer on an application with 1 choice
These changes should also apply to first applications that have only 1 choice.
> Tweaks for accepting or declining offers

- app/assets/sass/components/_status-indicator.scss
- app/data/dummy-application.js
- app/filters.js
- app/views/_includes/item/reference.njk
- app/views/_includes/review/references.njk
- app/views/application/index.njk
- app/views/application/references/action.njk
- app/views/application/references/candidate.njk
- app/views/application/references/email.njk
- app/views/application/references/name.njk
- app/views/application/references/relationship.njk
- app/views/application/references/start.njk
- app/views/application/references/type.njk
* Persist individual reference statuses on application
* Update design of status indicator
* Add and update content supporting reference states
* Update actions on reference summary card
* Reinstate school based reference and examples
* Move candidate name to end of referee flow
* Move referee type to beginning of referee flow
> Decoupled references tweaks

- app/views/_includes/review/choices.njk
- app/views/_includes/review/contact-details.njk
- app/views/_includes/review/degrees.njk
- app/views/_includes/review/english-language.njk
- app/views/_includes/review/gcse.njk
- app/views/_includes/review/incomplete.njk
- app/views/_includes/review/interview.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/_includes/review/personal-details.njk
- app/views/_includes/review/personal-statement.njk
- app/views/_includes/review/reasonable-adjustments.njk
- app/views/_includes/review/references.njk
- app/views/_includes/review/school-experience.njk
- app/views/_includes/review/subject-knowledge.njk
- app/views/_includes/review/suitability.njk
- app/views/_includes/review/work-history.njk
- app/views/application/review.njk
- app/views/application/submitted.njk
Update content we use for incomplete section messages to match production (and update message we show for decoupled references)
> Update incomplete messages

- app/routes/application/references.js
- app/views/_includes/review/references.njk
- app/views/_layout.njk
- app/views/application/index.njk
- app/views/application/references/action.njk
- app/views/application/references/candidate.njk
- app/views/application/references/relationship.njk
- app/views/application/references/review.njk
- app/views/application/submit.njk
- app/views/emails/reference-2-given.njk
- app/views/emails/reference-given.njk
* Ask for candidate name (if not yet given) at point candidate makes reference request
* Add ability to delete cancelled/declined/failed reference requests
* Review content around needing 2 references to have been given before you can submit
* Change language from ‘submit’ to more along the lines of ‘sending to training providers’
* Update emails when 1 and 2 references given
> Decoupled references (post UR playback)

- app/routes/application/references.js
- app/views/_includes/item/reference.njk
- app/views/_includes/review/references.njk
- app/views/application/references/action.njk
(Addresses https://github.com/DFE-Digital/apply-for-teacher-training/pull/3205)
Remove ‘Change’ link next to email, and instead add a ‘Retry request’ action to the summary card header:
This takes you to a page where you can resend request, and change email (repopulated with previous address used):
Summary card status is changed to ‘Awaiting response’ and event added that says ‘Request sent to [new email address]’:
> Retry reference request

- app/views/application/references/start.njk
Include content on SD Salaried courses.
Content to encourage candidates to ensure employers give full references.
@paulrobertlloyd Can you check the CTA on this page too please? Not sure if I've broken something.
> Content update - references start

- app/views/application/references/review.njk
When a candidate has requested 1 reference they are prompted to add another. Remove content about adding as many refs as you like.
When a candidate has requested 2 or more references they are reminded that they can add more. And that we cancel any requests after they've received 2.
> Content change for reference review page

- app/views/reference/comments.njk
For MVP we need to tell referees that the reference has to be done in one sitting.
Copy on top of the reference submission page to inform the referee.
@paulrobertlloyd Could you check that this is ok, please? Does it need the warning component or any other to differentiate it from the reference advice text, do you think?
Having considered other places for this copy, I think this probably the best. If we put it in the email it could put referees off at an early stage and they might not come back for a while. If they have this copy here I feel they'd be more likely to carry on.
> Content: referee cannot save and return

- app/views/index.njk
@frankieroberto @paulrobertlloyd - could either or both of you cast your eyes over this additional content for the start page before I request the change with GDS, please?
NARIC statements give people who have qualifications from overseas their comparable UK qualifications/grades. 
We already link to the NARIC website on our start page. We don't tell candidates how much they cost or that they can get free statements through Get Into Teaching.
Include this content and move the 'If you studied overseas content' under the 'Get advice and support' H2
I think moving the content makes it flow better because of where we refer to Get Into Teaching (first referred to under Get advice and support), rather than just tagging it on the end of the current 'If you studied overseas' content.
Current …
> Update Start page to include free NARIC statement

- app/views/application/degree/naric.njk
- app/views/application/gcse/naric.njk
Change the NARIC content once 'No' is selected on the Qualifications/NARIC pages for degree and GCSEs.
This is to highlight to candidates that they can get free NARIC statements from Get Into Teaching. Candidates have to call the freephone number to get the free statements so I have removed the link to register.
> Change NARIC content in Qualifications

- app/data/countries.js
- app/views/application/contact-details/international-address.njk
Will investigate other options such as breaking multiline input from a textarea, but I think still that’s ripe with issues converting to a frame that’s suitable for sending to SRSs.
So, alternatively, we can repurpose the inputs we use for UK addresses, but adjust the input labels to show international alternatives. We could customise labels to specific countries, but not sure how much effort that’s worth given current number of international students.
I think the bigger issue is formatting of addresses when previewed; this is where they tend to differ.
| UK address | International address |
| - | - |
| ![uk-address](https://user-images.githubusercontent.com/813383/101066458-59041500-358e-11eb-9f0d-bfe5b1014d38.png) | ![international-address](https://user-images.githubusercontent.com/81338 …
> Collect multi-line international addresses

- app/data/application-single-choice.js
- app/data/application.js
- app/data/session-data-defaults.js
- app/filters.js
- app/routes/application/dashboard.js
- app/views/_includes/item/choice.njk
- app/views/_includes/review/choices.njk
- app/views/admin/states.njk
- app/views/dashboard/index.njk
This updates the prototype to show more different states and combinations of states in the post-submission phase.  These mostly now reflect the current production design (although the apply again prompt is still a bit different).
There is some information deliberately missing, as it hasn't yet been added to the live service:
* offer conditions (once accepted)
* reasons given by the provider for withdrawing an offer
* reasons given by a candidate for declining an offer or withdrawing an application
* ability to see previous applications and outcomes (if applying again)
This PR is mainly just laying groundwork for a rethink and review of these sections.
> Add additional application states to prototype

- app/routes/application/dashboard.js
Fix: If a candidate doesn't respond to an offer before the deadline, the status is shown as "Offer declined" not "Unsuccessful".
> Fix: Show status as "Offer declined" if declined by default

- app/views/_includes/review/work-history.njk
The [GOV.UK style guide](https://www.gov.uk/guidance/content-design/writing-for-gov-uk#date-ranges) says:
> Use ‘to’ instead of a dash or slash in date ranges. ‘To’ is quicker to read than a dash, and it’s easier for screen readers.
Thanks @adamsilver for spotting this.
> Change dash to "to" between months

- README.md
- app/utils/index.js
When switching to a new machine, it took me a good few minutes to decrypt this error message, caused by the lack of the Notify API key, and look up what the expected environment variable should be:
```bash
/apply-for-teacher-training-prototype/node_modules/notifications-node-client/client/api_client.js:20
this.apiKeyId = arguments[0].substring(arguments[0].length - 36, arguments[0].length);
^
TypeError: Cannot read property 'substring' of undefined
```
This changes makes the use of Notify optional, enabling a faster start for designers and developers who don’t need to test email notifications.
> Make the use of GOV.UK Notify optional

- app/views/_includes/review/personal-details.njk
Update personal details review page to be consistent with residency page.
We've changed the label for the Yes radio text box to: 'What is your immigration status?'
On the review page, the label is 'Residency status' - change this to 'Immigration status' for consistency and to avoid any confusion.
> Update personal details review page

- app/data/application.js
This is only needed for international candidates
> Remove 'has-grade' answer

- app/routes/application/dashboard.js
- app/routes/application/decision.js
- app/views/_includes/item/offer.njk
- app/views/application/decision/view.njk
- app/views/dashboard/_confirmation_banner.njk
- app/views/dashboard/_course-choice-conditions.njk
- app/views/dashboard/_course-choice-interview.njk
- app/views/dashboard/_course-choices.njk
- app/views/dashboard/_guidance.njk
Content tweaks following user research.
Changes:
* "Details from provider:" changed to "Information from provider" as it’s often not that detailed.
* Added line "The provider will send more details about the interview by email." beneath interview content given by provider.
* Changed "You had an interview scheduled for..." to "You had an interview on..." to help differentiate it from future tense and to remove implication that you might not have attended.
* Added line "The provider will be in touch if they want to invite you to an interview." if the course is awaiting decision but no interviews schedule yet, rather than displaying this at the top of the page.
* Moved "You can wait to hear back from everyone before you make a decision." from the top of the page to beneath the "Respond to …
> Dashboard content design tweaks

- app/routes/application/dashboard.js
- app/views/_includes/item/feedback.njk
This [is being removed](https://bat-design-history.netlify.app/manage-teacher-training-applications/removing-the-future-applications-question-from-reasons-for-rejection/) from the structured feedback, following research showing it was not particularly helpful.
> Remove "interested in future applications" feedback

- app/data/application.js
- app/routes/application/dashboard.js
- app/views/_includes/item/feedback.njk
- app/views/admin/states.njk
This adds some more examples of feedback given for unsuccessful applications, for use in research.
Examples included:
1. Actionable feedback - ie things that can be immediately fixed by rewriting personal statement and subject knowledge sections.
2. Vague feedback - fairly generic feedback which doesn't offer any specific advice, but is still tied to certain sections.
3. Qualifications feedback - feedback that the qualifications (Maths GCSE and degree) were insufficient.
> Add feedback variants for research

- app/data/application-apply-again-with-choice.js
- app/data/application-international.js
- app/data/application-single-choice.js
- app/data/application-with-choices.js
- app/data/application.js
- app/routes/application/school-experience.js
- app/views/_includes/item/school-experience.njk
- app/views/_includes/review/contact-details.njk
- app/views/_includes/review/gcse.njk
- app/views/_includes/review/interview.njk
- app/views/_includes/review/personal-details.njk
- app/views/_includes/review/personal-statement.njk
- app/views/_includes/review/reasonable-adjustments.njk
- app/views/_includes/review/school-experience.njk
- app/views/_includes/review/subject-knowledge.njk
- app/views/_includes/review/suitability.njk
- app/views/_includes/review/work-history.njk
- app/views/application/choices/another.njk
- app/views/application/index.njk
- app/views/application/other-qualifications/details.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/other-qualifications/review.njk
- app/views/application/reasonable-adjustments/index.njk
- app/views/application/review.njk
- app/views/application/school-experience/index.njk
- app/views/application/school-experience/review.njk
- app/views/application/school-experience/role.njk
- app/views/application/suitability/index.njk
On making first pass at flight check fixes, broke how section and application review pages appear in different states.
This PR fixes these issues by determining if a section has been entered (some or all fields have values) and completed (section marked as completed). When we come to iteration 2 of flight check, some of this logic may change or go away, so this is an interim solution to make it so that the application works properly again. Hopefully.
This PR also reverts some of the section ordering and changes made for interaction 1 of A levels fixes, and uses the new section ordering instead:
* English GCSE or equivalent
* [English as a foreign language assessment]
* Maths GCSE or equivalent
* [Science GCSE or equivalent]
* A levels and other qualifications
* Degree
A separate PR will …
> Post flight check spike fixes

- app/views/application/index.njk
This adds some guidance on course selection to the application page, as it is not always read on the Choose your course page.
> Add guidance on how many courses you can select for apply again

- app/views/application/decision/view.njk
Two small changes:
* Add a paragraph back in with a link to the teacher training adviser service.
* Remove caption before the h1 (this was already done in production, but not in the prototype)
> Add teacher training adviser reference

- app/views/dashboard/_course-choices.njk
We don't need to show the interview information on the dashboard when a course has been offered, accepted, withdrawn or unsuccessful.
> Only show interviews information when awaiting decision

- app/views/dashboard/_previous-applications.njk
These help push the Previous applications section further away from the rest of the content, as they're likely a lot less important.
> Add section break classes

- app/filters.js
- app/routes/application/dashboard.js
- app/views/_includes/item/choice.njk
- app/views/_includes/review/choices.njk
- app/views/dashboard/_course-choices.njk
- app/views/dashboard/_guidance.njk
Currently we display "Conditions met" as the status for courses where the provider has confirmed that the candidate has met all the conditions required for the course.
However, some courses don’t have any conditions at all, or at least any conditions specified on the service (there might be some administrative conditions off-service). In these scenarios, the status doesn’t make sense.
Whilst we _could_ have a different status label for those who have accepted unconditional offers only, it would be simpler if we could find a new label that works in all scenarios.
"Offer confirmed" is potentially a more positive-sounding label than "Conditions met", and is also consistent with the language used on the service when the candidate has not yet met the conditions, which states:
> You’ve accepted …
> Change "Conditions met" to "Offer confirmed"

- app/routes.js
- app/routes/send-email.js
- app/routes/survey.js
- app/views/survey/index.njk
This is an alternative to #484, and adds the survey to the post-submission flow, just before taking the user to the application dashboard showing the confirmation banner. To make it a clearer that the free-text is optional, "(optional)" is added to the label.
➡️  [Review this journey](https://apply-beta-p-add-survey-jveeye.herokuapp.com/application/12345)
> Add survey to post-submission flow

- app/assets/sass/components/_inset-text.scss
- app/views/_includes/review/personal-statement.njk
- app/views/_includes/review/subject-knowledge.njk
Maybe the pink is unnecessary? Do the headings help?
> Use standard inset text and headings

- app/views/application/personal-statement/review.njk
- app/views/application/subject-knowledge/review.njk
To be consistent with the REVIEW status tag, if the candidate is applying again and a section is marked as needing review, the label of the "I have completed this section" checkbox should change to "I have reviewed this section".
> Change "completed" checkbox to "reviewed" if there was feedback

- app/routes/application/choices.js
- app/views/application/choices/found.njk
- app/views/application/choices/index.njk
- app/views/application/choices/location.njk
- app/views/application/choices/pick.njk
- app/views/application/choices/provider.njk
This applies a bunch of content and UI changes from the course choice flow in production to the prototype.
Changes:
* "Have you chosen a course to apply to?" changed to "Do you know which course you want to apply to?"
* "Pick a course location" changed to "Which location are you applying to?"
* Location names in radios lose their boldness
* Course selection changed from autocomplete to radios to match production
* Provider autocomplete gains a dropdown arrow
* Summary cards on review page are only 2/3rds width
I’ve quite possibly still missed some things. Also need to get my head around how the Apply -> Find -> Apply integration works.
> Update course choice pages to match production

- app/assets/sass/application.scss
- package.json
The [new link styles](https://github.com/alphagov/govuk-frontend/releases/tag/v3.12.0) are currently opt-in. The main differences are:
> Links now have underlines that are consistently thinner and a bit further away from the link text.
>
> Links also have a clearer hover state, where the underline gets thicker to make the link stand out to users.
Version 3.13.0 of govuk-frontend [disables ink skipping of underlines in hover state](https://github.com/alphagov/govuk-frontend/pull/2251) to avoid large gaps appearing in the underline on hover in Safari and Firefox.
> Upgrade govuk-frontend and enable new links styles

- app/routes/application/choices.js
- app/views/application/choices/another.njk
- app/views/application/choices/find.njk
- app/views/application/choices/found.njk
- app/views/application/choices/index.njk
- app/views/application/index.njk
As we no longer need to mention the UCAS dual-running from September, we can remove the interstitial page which explains this:
> <img width="730" alt="Screenshot 2021-06-25 at 11 19 47" src="https://user-images.githubusercontent.com/30665/123410485-4cd1ba80-d5a7-11eb-9332-1a9ff6cfe941.png">
The "You can apply for up to 3 courses." message is already on the application index page.
Instead, from the application index page, the "Choose your courses" link can go directly to the "Do you know which course you want to apply to?" page.
If you delete a course choice from the course choices index page, you are redirected to the "Do you know which course you want to apply to?" page again, rather than being shown an empty page.
(Also fixes some back links)
> Remove course choices interstitial pages

- package.json
version 5 requires sass to be installed separately
> Revert gulp-sass upgrade

- app/views/application/index.njk
This fixes a bug where the "Completed" tags were still showing up even if you marked a section as "No, I’ll come back to it later"
> Bugfix: "incomplete" tags

- app/routes/application/dashboard.js
- app/views/admin/states.njk
- app/views/dashboard/_course-choices.njk
The provider team have added a feature enabling provider to withdraw an application at the candidate’s request.
This shows how we can represent this to the candidate in the post-submission dashboard.
An extra line is added to encourage candidates to contact support if they didn't request their application to be withdrawn.
The rest of the page, including the call to action to apply again, is unchanged.
> Show application withdrawn by provider

- app/routes/application/choices.js
The course length, type and start date of courses weren’t being filled out when adding courses:
This fixes this, by taking the course type from the courses data JSON file, and hardcoding the other 2.
> Bugfix: missing course details when adding course

- app/filters.js
- app/utils/index.js
When toArray is called on an `undefined` or `null` object, an empty array should be returned.
This prevents errors occurring if you try to filter the returned object, such as:
```
TypeError: Cannot read property 'filter' of undefined
```
> Bugfix: toArray should always return an array

- app/data/application.js
- app/data/session-data-defaults.js
- app/routes/application/choices.js
- app/utils/filters-with-app-context.js
- app/utils/index.js
- app/views/_includes/item/choice.njk
- app/views/admin/states.njk
This adds a warning message to the Course choices section (and the review page) if the candidate’s highest degree grade doesn't meet the minimum required for a course.
If the degree grade is predicted, the message is slightly different:
If the degree grade cannot directly be compared to the minimum requirement (eg because it’s an international degree), or if the candidate meets the minimum degree required, then just the minimum requirement is shown:
> Show warning if degree class doesn't meet minimum required

- app/views/_includes/item/degrees.njk
- app/views/application/degree/grade.njk
Updates following a content review:
* Question changed from "What grade do you think you’ll get" / "Predicted grade" to "What grade do you expect to get?" / "Expected grade"
* The guidance for expected grades has been changed, to make it more relevant to the question being immediately asked.
* Guidance uses hint text rather than inset text, for improved accessibility
* Non-UK version has visible label rather than hidden, using the same question wording as UK version
> Change "expected grade" content

- app/assets/sass/components/_status-indicator.scss
- app/data/application.js
- app/filters.js
- app/views/application/index.njk
- app/views/application/references/relationship.njk
- app/views/application/references/review.njk
- app/views/application/references/start.njk
We’ve changed a bit of the content around references, as well as the status indicators. But we haven’t prototyped the new reference selection process.
This PR updates the application menu and other pages to bring them closer inline with what’s on (or soon will be on) prod, but without adding the select 2 references flow.
Is that a problem do we think?
> Half-update references section, minus selection flow

- app/routes/application/personal-information.js
- app/views/_includes/review/personal-information.njk
- app/views/application/personal-information/residency-sponsorship.njk
- app/views/application/personal-information/residency.njk
This adds a new question if someone indicates that they do not yet have the right to work or study in the UK.
The question asks them how they will gain the right to work or study in the UK, with 2 possible answers:
* A visa sponsored by a course provider
* Another route
(If they select the second one, they are asked to give details).
The need for this question is so that:
1) if they are planning to get a visa sponsored by a provider, we can warn them and give guidance if they apply for a course by a provider who cannot offer this.
2) if they are gaining the right to work or study in the UK in some other way, the details they give may help providers to understand the context of the candidate’s immigration status, which may avoid them rejecting the candidate on the ground that they cannot …
> Add follow-up residency question

- app/views/application/personal-information/residency.njk
This changes "Not yet, or not sure" to just "Not yet".
This is because:
* If someone selects this answer, we show a follow-up question asking how they will get the right to work or study. This doesn't make sense if they're not sure.
* We should help a candidate to answer the question instead, or signpost them to a teacher training adviser
* If we are not sure of their right to work or study, we can't offer relevant guidance when applying for courses which may or may not sponsor visas.
If removing this proves to be a big blocker for some candidates, we could consider adding "Not sure" back as a third option instead.
> Remove "not sure" from label on "Right to work or study in the UK" question

- app/data/session-data-defaults.js
- app/routes/application/gcse.js
- app/views/_includes/item/choice.njk
- app/views/_includes/item/gcse.njk
- app/views/admin/states.njk
- app/views/application/gcse/equivalency.njk
- app/views/application/gcse/grade.njk
- app/views/application/gcse/index.njk
- app/views/application/gcse/no-pass-grade.njk
- app/views/application/gcse/not-yet.njk
- app/views/application/gcse/year.njk
This aims to give candidates some guidance (or warnings) in the scenario that they:
* are currently (re)taking a GCSE, but are applying to a course which does not accept pending GCSE
* do not have a GCSE C or above and are not currently studying for one, and are applying for a course which does not accept equivalency tests
We also reviewed the content of the existing GCSE pages.
The initial GCSE question has been simplified, to remove reference to the C/4 grade, as this is caught later:
If the candidates have a GCSE in English, the following page has been simplified, with the reference to English language as being preferred removed:
If candidates select that they do not yet have this qualification, they get asked if they are currently studying for one:
If they say yes, they can give …
> Update GCSE question and guidance

- app/views/application/gcse/index.njk
This is to try and avoid ambiguity in "English" qualifications, which could be "English as a subject" (eg as taught in the UK) vs "English as a foreign language" (as may be taught in non-English speaking countries).
> Tweak to GCSE question page

- app/views/admin/index.njk
- app/views/reference/comments.njk
- app/views/reference/index.njk
- app/views/reference/review.njk
- app/views/reference/safeguarding.njk
We currently tell referees that they need to complete the reference in a "one sitting". However they _can_ save and come back to it at any time, using the original link sent to their email.
Feedback from referees has indicated that they find the requirement to complete the reference in a single sitting to be stressful, especially given that the reference takes longer than they initially expect.  Some referees may work around this by copying and pasting to and from a separate file, but this can be cumbersome, and means they might not see the word count straight away.
To address this, we are changing the content to make clear that they can return to the form after saving it. The buttons are also relabelled from "Continue" to "Save and continue". However the button on the page with the 500 …
> Make it clear you can return to reference

- app/views/application/references/review.njk
The referrer string shouldn't be added here, as it prevents the flow from working (redirected back to the review page after answering the first question).
> Bugfix: references flow

- app/routes/application/other-qualifications.js
- app/views/_includes/item/other-qualifications.njk
- app/views/_includes/review/other-qualifications.njk
- app/views/_includes/review/references.njk
- app/views/application/index.njk
- app/views/application/other-qualifications/details.njk
- app/views/application/other-qualifications/index.njk
- app/views/application/other-qualifications/review.njk
- app/views/application/other-qualifications/type.njk
- app/views/application/review.njk
This simplifies the "A levels and other qualifications" flow so that the "What type of qualification do you want to add?" no longer contains an "I do not want to add any A levels and other qualifications" answer, in order to reduce the complexity of the question, and to more easily represent the candidate’s answers on the application review and within Manage.
Instead, candidates are routed through the review page, which contains the guidance about why it is a good idea to add A levels and other qualifications. This also means that this content is still visible even after adding the first qualification, to remind candidates that they can continue to add other qualifications.
Additionally, on the details screen, the font size of the labels has been reduced, and the "Do you want to add …
> Simplify "other qualifications" flow

- app/data/session-data-defaults.js
- app/routes/application/degree.js
- app/views/application/degree/review.html
This updates the prototype to prevent candidates from marking the degree section as complete if they've only added Foundation degrees.
To do this, the "Have you completed this section?" question is removed from the bottom, and the "Add another degree" buttons switches to the primary green colour (rather than secondary grey). The guidance is also shown.
> Prevent application submission where only Foundation level degrees have been entered

- app/routes/application/references.js
- app/routes/application/review.js
This no longer works, for some reason.
Refactoring so that error messages on review page use a query string instead.
Reference flash messages will have to be refactored later.
> Bugfix: remove references to req.flash

- package-lock.json
- package.json
[acorn](https://github.com/acornjs/acorn) isn't directly used by our code, but is a sub-dependency.
> Remove acorn as direct dependency and update it

- package-lock.json
- package.json
This aims to prevent a Heroku deploy message saying:
```
- Dangerous semver range (>) in engines.node
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
```
It should also reduce any errors caused by developers using different versions of node locally.
> Use node 16

- app/views/dashboard/_course-choices.html
Changes the "Request a reference" button to secondary grey colour with the text "Request another reference", as it now doesn't need to be so prominent at this point as they've already requested at least 2.
> Change "Request a reference" button colour and text

- app/views/_includes/item/reference.html
This switches the title in the summary card on the references review pages to use the name of the referee instead of "First reference", "Second reference" etc.
This is because:
* the names might be easier to scan
* the order isn't important at all, but using "first", "second" etc might falsly imply that it is
* ordinal numbers can be slow to read, particularly when getting up to higher numbers ("Eleventh", "Sixteenth") – although it's unlikely many candidates add more than 10
* Using "reference" might imply that the reference has been collected (or will be), but in the new flow, the person isn't contacted for a reference until later.
There should always be a name, as the reference isn't saved to the database until after a name has been added.
One possible downside is that the name is now …
> Use referee name in summary card titles instead of 'First reference' etc

- app/routes/reference.js
- app/views/admin/index.html
- app/views/reference/comments.html
- app/views/reference/confirmation.html
- app/views/reference/decline.html
- app/views/reference/email-request.html
- app/views/reference/index.html
- app/views/reference/relationship.html
- app/views/reference/review.html
- app/views/reference/safeguarding.html
- app/views/reference/start.html
This updates the referee flow, now that references are given after an offer has been accepted rather than before an application has been submitted.
Given that references are now purely for safeguarding purposes rather than to assess candidates, the reference can now be focused on providing shorter, factual information.
The examples in the bulleted list vary depending on the reference type (academic, professional, school-based or character).
The rest of the flow has been updated slightly too, following a review.
🗂️ [Trello card](https://trello.com/c/v8ZUInA0/561-revised-reference-interface-for-referees)
> Update referee flow

- app/views/application/degree/grade.html
- app/views/reference/comments.html
We don't think (backed up by some research) that most universities give students "predicted grades", and we don't think most academic referees would be able to confirm these.
| Before | After |
|----|----|
| ![degree-before](https://user-images.githubusercontent.com/30665/190420045-661b0556-1a41-49c6-9020-8b5eb8e5e89d.png) |  ![grade-after](https://user-images.githubusercontent.com/30665/190420058-70f5085a-a34f-447f-a182-3d4ba75b7e6e.png) |
| ![reference-before](https://user-images.githubusercontent.com/30665/190420092-e5856dde-06ff-4471-909d-37424f64f590.png) | ![reference-after](https://user-images.githubusercontent.com/30665/190454110-00941a39-71f7-4d73-803d-2230c1c73c7d.png) |
> Remove suggestion that expected degree grades should be confirmed by academic referees

- app/data/application.js
- app/data/session-data-defaults.js
- app/filters.js
- app/routes/admin.js
- app/routes/application.js
- app/routes/application/dashboard.js
- app/routes/application/references.js
- app/routes/dashboard/references.js
- app/views/_includes/item/reference.html
- app/views/dashboard/_course-choices.html
- app/views/dashboard/references/action.html
Updates the reference statuses to use slightly updated wording and colours, to try and increase clarity.
| Status  | Colour |
| ------------- | ------------- |
| Not sent | Blue |
| Requested | Purple |
| Received by training provider | Green |
| Request cancelled | Orange |
| Cannot give reference | Red |
| Request failed | Yellow |
> Update reference statuses

- app/views/reference/comments.html
- app/views/reference/email-request.html
- app/views/reference/index.html
- app/views/reference/relationship.html
- app/views/reference/review.html
- app/views/reference/safeguarding.html
- We removed content to focus on the most important things. For example, we removed bullet about confirming how long the referee has known the candidate. The referee cannot prepare for this question as they don't know what the candidate has written.
- We mentioned in the lead in to the link that it can be used to say that a referee cannot give a reference. We want them to do that rather than do nothing, so that the candidate knows they need to ask someone else.
- We added content to tell referees that if they use the service to say they can't give a reference, they will no longer receive emails about it. 
- Changed "I am" to "I'm" to fit the usual style for the service.
- The heading has been changed from "Confirm how you know ((candidate))" to "Confirm how ((candidate)) knows you". This …
> Referee flow amends

- app/assets/javascripts/application.js
- app/assets/sass/application.scss
- app/views/_includes/item/feedback.html
This would add some buttons to allow candidates to say whether the feedback given when they are rejected is helpful or not.
🗂️ [Trello card](https://trello.com/c/Mg1wH7xS/700-ask-candidates-whether-providers-rejection-feedback-was-useful)
In the dashboard, a single question would be shown beneath the feedback:
Clicking a button would replace the buttons and text with a confirmation message:
...or if they said it was not helpful:
(Ideally we'd do this via javascript to avoid a page reload)
> Survey users on whether provider rejection feedback is helpful

- app/data/application.js
- app/data/session-data-defaults.js
- app/routes/application/choices.js
- app/routes/delete.js
- app/views/_includes/review/choices.html
- app/views/admin/states.html
- app/views/application/choices/delete.html
- app/views/application/review.html
This would allow candidates to add courses which aren't yet open for applications, but would warn them and prevent the application being submitted.
This would hopefully make it more obvious (than just not allowing them to find the course in the dropdowns/radios), and allows candidates to get their whole application ready, waiting for the course to open. Alternatively they can choose a different course.
We can use the same approach for when a course is "full" / has no vacancies.
🗂️ [Trello card](https://trello.com/c/l7u2mGiK/762-allow-candidates-to-add-courses-not-yet-open-to-their-application-but-not-submit-the-application-yet)
➡️  [Preview](https://apply-tt-pr-726.herokuapp.com/application/19415)
> Show message if you can't apply to a course

- app/views/accepted/index.html
- app/views/accepted/select-ske-provider.html
This moves the link to the SKE course directory from the main post-offer interface to within the "Select a provider" screen.
The button is now also green.
> SKE courses: move link to directory within "Select" page

- app/routes/application/dashboard.js
- app/views/_includes/item/offer.html
- app/views/accepted/index.html
- app/views/admin/states.html
- app/views/dashboard/_course-choices.html
This changes the view for "unconditional" offers, where no conditions are set in Manage or via the API, so that we always display some guidance text about reference being checked, and any other conditions which may have been mentioned off-service.
🗂️ [Trello card](https://trello.com/c/55tomdM9/900-mention-references-for-an-unconditional-offer-on-candidate-dashboard-and-details-of-offer-page)
> Unconditional offer guidance

- app/views/dashboard/index.html
This tweaks the success message shown when submitting to:
* remove the duplicate word "successfully" (banner already has the title "Success")
* remove the line about receiving emails from the banner and move it to body text, so that it'll be shown even on later page loads
* change "when something changes" to "when the provider makes a decision" to be more specific.
Technically you'll also be emailed about other changes, eg being rejected automatically, invited to an interview, or being withdrawn (at your request) but those don't feel like they need to be explicitly mentioned.
🗂️ [Trello card](https://trello.com/c/XIuydIxs/992-improve-our-success-messaging-when-a-candidate-submits-an-application)
> Tweak success message

- app/routes/application/dashboard.js
- app/views/_includes/item/feedback.html
- app/views/dashboard/_apply-again.html
When a provider rejects a candidate, we want to show some text to help the candidate take the next step and keep them in the application journey. We also know that sometimes the rejection reasons from providers is not helpful.
Trello ticket: https://trello.com/c/zmcV9v7v/495-r4r-draft-boiler-plate-feedback-text
When all 3 applications are unsuccessful, we would show some 'boiler plate' content above the applications to help them onto the next step.
Image below shows the text above the rejected applications, each bullet point would only show depending in what 'rejection reason' a provider chooses. From analysis, the majority of providers only ever select 1 or 2 reasons. So in the screenshot below a candidate would mostly only see 1 or 2 bullet points (I've included more just to see what it …
> Boiler plate content for reasons for rejection

- app/views/application/gcse/index.html
- app/views/application/references/index.html
When checking validation errors, we noticed a lot of candidates from Nigeria are adding in their Nigerian O level grades to the 'O level section' under qualifications. There is nothing to distinguich that we're asking for UK O levels. They should be adding in their level results in the 'non-UK qualification' section. We've made some small tweaks to make this clearer for people.
Changed:
- 'O levels' to 'UK O level (before 1989)'
- separated 'non UK qualifications' by using an 'or' and renaming it to 'Qualification from outside the UK'
https://trello.com/c/NGfBFZFn/1161-make-it-clearer-that-o-level-means-a-uk-o-level-and-not-a-nigerian-one
> O level qualifications

- app/assets/sass/application.scss
- app/assets/sass/components/_header.scss
- app/assets/sass/components/_phase-banner.scss
- app/assets/sass/components/_secondary-nav.scss
- app/routes.js
- app/views/account/change-email-address.html
- app/views/account/check-email.html
- app/views/account/create-account.html
- app/views/account/index.html
- app/views/account/sign-in.html
- app/views/application/index.html
- app/views/dashboard/index.html
- app/views/index.html
- app/views/layouts/main.html
This adds a navigation bar to the candidate interface, even though it only has 1 item in it for now (plus "sign out"). This is to enable further items to be added when continuous applications is launched.
🗂️ [Trello card](https://trello.com/c/wFS59p9L/1502-design-the-candidate-navigation-bar)
Changes:
* No longer show email address in black header bar
* Move sign out link from black header bar to grey navigation bar, aligned right
* Add "Your application(s)" as the first (and only) navigation item, and show it as selected.
Note: For now, the capitalisation of "Your application(s)" should follow the convention used on the service, which is:
* singular when not yet submitted
* singular if submitted but there was only 1 course chocie
* plural if submitted and there were 2+ course choices
* …
> Add navigation bar and change header

- app/views/application/equality-diversity/sex.html
The back link navigated to the interstitial page that we decided to remove. Caused some confusion for devs.
> Update back link on E&D survey.html

- app/views/application/safeguarding/index.html
- app/views/application/submit.html
We previously removed the 'additional information' question and agreed to merge the information about DBS checks into the question about declaring safeguarding information on the application form.
There is no 'after' as this page is now removed
> Merge content about safeguarding

- app/routes.js
- app/routes/details/index.js
- app/views/applications/index.html
- app/views/applications/review.html
- app/views/details/index.html
This changes the behaviour of the prototype so that candidates can 'add' a course even if they have not yet completed all sections of their details.  However they cannot yet submit any applications.
This is to enable the existing behaviour where clicking the "Apply" link on Find adds the course to your application regardless of the states of the rest of your application.
> Allow courses to be added before all sections completed

- app/views/accepted/index.html
- app/views/layouts/main.html
We designed this page immediately on production but did not update the prototype. Small change to match the H1 and navigation tab content so people don't get confused.
This page shows when a candidate has accepted an offer, but if still waiting for their conditions to be met.
**BEFORE:**
**AFTER:**
> Match content on prototype to production

- app/views/applications/index.html
I noticed on the prototype when an application is in "offer received' status, the link says 'Remove', but it should say 'Withdraw"
Small fix to update that.
**BEFORE:**
**AFTER:**
> Fixed 'withdrawal' and 'remove' link on application page

- app/views/applications/index.html
- app/views/applications/provider-already-selected.html
We removed a feature allowing candidates to add multiple courses to the same application to the same provider.
We decided this was not MVP for continuous applications.
I've edited to content to reflect this so it does not confuse the devs when building (the first bullet point in the images below)
I've also removed mention of draft applications when a user has applied to 4 courses and cannot apply any more.
**Before:**
**After:**
> Updated content to remove mention of adding other courses

- app/views/applications/review.html
As part of our discussions on Tue 8/8 on building the submission journey to continuous applications, we discussed have some content before a candidate submits to confirm their info in correct.
We used to have this in the service, but somehwere along the line it was removed from the prototype. I've added it back for Tomas to build.
> Adding a confirmation statement before submitting an application.

- app/views/account/check-email.html
- app/views/account/index.html
I've been contacted by a few people who get confused when signing in to the Apply prototype. They think they have to sign in, but they do not. They also miss the secret link on the final sign in page.
I've added a link to skip the sign in screens to make it easier for people.
I've also made the hidden link a real link
> added skip link to go straight to prototype

- app/views/application-process.html
The devs will be updating this page soon so I've removed the old guidance that was commented out in the code so there's no confusion.
I also edited a sentence that said you can apply for courses at 4 different training providers. This is incorrect, you can apply to the same provider if you want to.
**Before:**
**After:**
> Removed old guidance and updated a sentence in the new one

- app/views/application-process.html
I changed 'a month' to '30 working days' in the application process guidance, as that is more accurate. This came up in a conversation with GiT team so we should be consistent.
Before:
After:
> Added '30 working days' to application guidance for clarity

- app/views/applications/index.html
We've seen a lot of candidates withdraw applications quickly  and they are fast approaching 20 applications.
We decided to put a 'cap' of 15 unsuccessful applications to stop candidates using all their choices too quickly.
We show this content when a candidate had 3 submissions and it will replace the inset text on the Your applications tab.
Trello ticket: https://trello.com/c/Iz3bbY7a/759-edit-content-where-a-candidate-has-submitted-4-applications-already
**Content before:**
**Content after:**
> Edited content to communicate cap of 15 unsuccessful applications

- app/views/details/index.html
The 'Free of charge" text on our Get help section on Apply is misleading for international candidates.
This PR removes that text and adds a link to the online chat on GiT.
Trello ticket: https://trello.com/c/ExTBmged/701-free-of-charge-phone-number-content-is-misleading
> Removed 'Free of charge text"

- app/views/details/personal-information/immigration.html
After testing the 'Right to work or study' page, there were recommendations to iterate the content.
Changes include:
- Left H1 the same as people seemed to be familiar with this language/phrase
- Moved link to the bottom and shortened it so it doesn't stand out so much (the link text now also matches the H1 of the page it links to)
- Last paragraph is now moved up, as when people read this, they found it useful but the long link was distracting
- Changes the first sentence to not repeat the H1, instead it explains 'right to work or study' in plainer language (why didn't I think of this before!?)
> Iterated content on 'Right to work or study page

- app/routes/reference.js
- app/views/_components/application-status/macro.njk
- app/views/applications/confirm.html
- app/views/applications/index.html
- app/views/applications/review-application.html
- app/views/details/references/index.html
- app/views/layouts/main.html
- app/views/reference/index.html
- app/views/reference/review.html
- app/views/reference/share.html
Giving referees the ability to state whether a reference is confidential or not.
[Ticket](https://trello.com/c/RAFpL0Gm/171-references-content-to-clarify-confidentiality-choice)
[Content source](https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B8664D7BA-647C-4615-88CB-23C9B7430B32%7D&file=Degree%20relevance%20matching%20-%20Rules.docx&action=default&mobileredirect=true)
> Confidential references

- app/routes/applications.js
- app/routes/details/references.js
- app/views/applications/interruption-module.html
- app/views/details/references/email-warning.html
- app/views/details/references/email.html
- app/views/details/references/relationship.html
[Ticket with background info](https://trello.com/c/Janox9Gc)
**Updated hint text when entering email address:**
**Flight check when entering a personal email address for a reference:**
**Flight check when trying to submit application which contains a personal email address for a reference:**
> Adding a flight check for applicants supplying a personal email address for a referee
